### PR TITLE
[3806] Add an API to condition the application of participant migration

### LINKED ISSUE #3806: MigrationParticipant implementation broke conventional ExtendedMetadata mechanism
I will use a UML meta model use case to describe this use case.

In the UML metamodel, we can find the following annotation:

image

My understanding is that the feature `ownedGroup` needs to be serialized as `group`. (Note there is also a `group` EReference but this one is Derived/Transient/Volatile).

```xml
<packagedElement xmi:type="uml:Activity" xmi:id="_B6tXUEj9Ee-Rp58iMjoc3A" name="Activity1" node="_Ddv3YEj9Ee-Rp58iMjoc3A">
    <node xmi:type="uml:InitialNode" xmi:id="_Ddv3YEj9Ee-Rp58iMjoc3A" name="InitialNode1"/>
</packagedElement>
```

But when this feature is read, it should fill the `ownedGroup` feature.

image

Previously in _Papyrus Web_, we removed the BasicExtendedMetadata object from the _ResourceSet_ by customizing the _EditingContextSearchService_ and the _EditingContextFactory_. In the new architecture, we replaced this behavior by doing the same in a custom _IEditingContextProcessor_.

However, this is not enough because it is now forced by the following services to plug the MigrationParticipant (since it inherits from BasicExtendedMetadata) behavior:

*  _org.eclipse.sirius.web.application.document.services.JSONExternalResourceLoaderService.getResource(InputStream, URI, ResourceSet)_
* _org.eclipse.sirius.web.application.editingcontext.services.ResourceToDocumentService.toDocument(Resource)_
* _org.eclipse.sirius.web.application.editingcontext.services.ResourceLoader.toResource(ResourceSet, String, String, String)_
* _org.eclipse.sirius.web.application.document.services.DocumentSanitizedJsonContentProvider.getContent(ResourceSet, String, InputStream)_

Resulting in the model in the database looking like:

```json
 {
    "id": "23b6df82-53ac-45ba-865b-2b6b5d61b420",
    "eClass": "uml:Activity",
    "data": {
        "name": "Activity1",
        "group": [
            {
                "id": "2886665f-5abb-4655-8b42-0398d904be94",
                "eClass": "uml:ActivityPartition",
                "data": {
                    "name": "ActivityPartition1",
                    "node": ["//Activity1/ActivityFinalNode2"]
                }
            }
        ],
        "node": [
            {
                "id": "644db420-110a-4ceb-99e0-6730d347d6f6",
                "eClass": "uml:ActivityFinalNode",
                "data": { "name": "ActivityFinalNode1" }
            },
            {
                "id": "18e257f0-f7f5-40ea-aed5-fcfc46c942a7",
                "eClass": "uml:ActivityFinalNode",
                "data": {
                    "name": "ActivityFinalNode2",
                    "inPartition": ["//Activity1/ActivityPartition1"]
                }
            }
        ],
        "partition": ["//Activity1/ActivityPartition1"]
    }
}
```

Whereas before it looked like this:

```json
 {
    "id": "641e61db-8806-4f26-80f0-110edc66146c",
    "eClass": "uml:Activity",
    "data": {
        "name": "Activity1",
        "ownedGroup": [
            {
                "id": "7ac88b8d-ced8-4dc2-8d53-0d5177473840",
                "eClass": "uml:ActivityPartition",
                "data": {
                    "name": "ActivityPartition1",
                    "node": ["//Activity1/ActivityFinalNode2"]
                }
            }
        ],
        "ownedNode": [
            {
                "id": "171cf2f7-a4c4-4450-860a-75bee44f76ad",
                "eClass": "uml:ActivityFinalNode",
                "data": { "name": "ActivityFinalNode1" }
            },
            {
                "id": "a0ddeaf5-01ec-4420-b78d-d1d72c462ff3",
                "eClass": "uml:ActivityFinalNode",
                "data": {
                    "name": "ActivityFinalNode2",
                    "inPartition": ["//Activity1/ActivityPartition1"]
                }
            }
        ],
        "partition": ["//Activity1/ActivityPartition1"]
    }
}
```

This causes the following exception when the model is loaded from the database:

```
java.lang.UnsupportedOperationException: JsonObject
    at com.google.gson.JsonElement.getAsString(JsonElement.java:187) ~[gson-2.10.1.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeMultipleNonContainmentEReference(GsonEObjectDeserializer.java:677) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeEReference(GsonEObjectDeserializer.java:497) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeData(GsonEObjectDeserializer.java:472) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeEClassifier(GsonEObjectDeserializer.java:446) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.loadObject(GsonEObjectDeserializer.java:407) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeMultipleContainmentEReference(GsonEObjectDeserializer.java:869) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeEReference(GsonEObjectDeserializer.java:491) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeData(GsonEObjectDeserializer.java:472) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.deserializeEClassifier(GsonEObjectDeserializer.java:446) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
    at org.eclipse.sirius.emfjson.utils.GsonEObjectDeserializer.loadObject(GsonEObjectDeserializer.java:407) ~[org.eclipse.sirius.emfjson-2.3.12-SNAPSHOT.jar:na]
```

EMFJson expects to load a flat ID list as it has encountered a non-containment EReference (`group`) but gets some structured data since it is, in fact, the content of the `ownedGroup` feature.

This problem arises because the _forced_ implementation in the _MigrationService_ does not delegate the computation that retrieves the feature from a name to its superclass implementation:

```java
@Override
public EStructuralFeature getElement(EClass eClass, String namespace, String eStructuralFeatureName) {
    EStructuralFeature structuralFeature = eClass.getEStructuralFeature(eStructuralFeatureName);
    for (IMigrationParticipant migrationParticipant : this.migrationParticipantsCandidates) {
        EStructuralFeature newStructuralFeature = migrationParticipant.getEStructuralFeature(eClass, eStructuralFeatureName);
        if (newStructuralFeature != null) {
            structuralFeature = newStructuralFeature;
        }
    }
    return structuralFeature;
}
```

Moreover, to make it work, we would need to be able to provide our own implementation of _BasicExtendedMetaData_ to override the following method _org.eclipse.emf.ecore.util.BasicExtendedMetaData.isFeatureNamespaceMatchingLax()_ so it can return true.

Maybe a solution would be for the two given services not to directly override the _JsonResource.OPTION_EXTENDED_META_DATA_ option but:

* First, check the ResourceSet if this option is set.
* If it is not, create a _BasicExtendedMetaData_.
* Then compose either the retrieved _ExtendedMetaData_ or the newly created one into the _MigrationService_.

Then modify the MigrationService so it delegates most of its behavior to the given _ExtendedMetaData_.

### PR DESCRIPTION
**Pull request by frouene**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/3806

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSearchService.java [hunk 1]
```diff
@@ -61,26 +52,16 @@ public class EditingContextSearchService implements IEditingContextSearchService
...
-                                       List<IEditingContextRepresentationDescriptionProvider> representationDescriptionProviders, List<IEditingContextProcessor> editingContextProcessors, MeterRegistry meterRegistry) {
+    public EditingContextSearchService(IProjectSearchService projectSearchService, IEditingDomainFactory editingDomainFactory, IEditingContextLoader editingContextLoader, MeterRegistry meterRegistry) {
         this.projectSearchService = Objects.requireNonNull(projectSearchService);
-        this.semanticDataSearchService = Objects.requireNonNull(semanticDataSearchService);
-        this.resourceLoader = Objects.requireNonNull(resourceLoader);
         this.editingDomainFactory = Objects.requireNonNull(editingDomainFactory);
-        this.representationDescriptionProviders = Objects.requireNonNull(representationDescriptionProviders);
-        this.editingContextProcessors = Objects.requireNonNull(editingContextProcessors);
+        this.editingContextLoader = editingContextLoader;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSearchService.java]: Objects.requireNonNull

**Review by sbegaudeau — APPROVED** [review]
