### PR TITLE
[4285] Fix direct edit when the palette is closed

### LINKED ISSUE #4285: After closing the palette with ESC, direct edit does not work

### PR DESCRIPTION
**Pull request by mcharfadi**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/4285

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx [hunk 1]
```diff
@@ -77,24 +77,39 @@ export const useDiagramDelete = (): UseDiagramDeleteValue => {
...
-    /*If a modifier key is hit alone, do nothing*/
+    const { key, target } = event;
     const isTextField = event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement;
-    if ((event.altKey && key === 'Alt') || (event.shiftKey && key === 'Shift') || isTextField) {
+
+    /*If a modifier key is hit alone, do nothing*/
+    if ((event.altKey && key === 'Alt') || (event.shiftKey && key === 'Shift') || isTextField || readOnly) {
+      return;
+    }
+    /*If the palette is opened, do nothing*/
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx]: 1- Why?
2- This does not work, it only works half the time so why?

Why can't I click an edge and use the key `Delete` to delete it?

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx [hunk 2]
```diff
@@ -29,20 +29,30 @@ export const useDiagramDirectEdit = (): UseDiagramDirectEditValue => {
...
-      const { key } = event;
+      const { key, target } = event;
       /*If a modifier key is hit alone, do nothing*/
-      const isTextField = event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement;
-      if ((event.altKey && key === 'Alt') || (event.shiftKey && key === 'Shift') || isTextField || readOnly) {
+      if ((event.altKey && key === 'Alt') || (event.shiftKey && key === 'Shift') || readOnly) {
+        return;
+      }
+
+      /*When the palette is opened, allow direct edit only with F2 so we can type in the palette search field*/
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx]: Why break the existing behavior that has worked for years on both desktop and web?

Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx]: Even that does not work properly, I can successfully bypass it sometimes to restore the original behavior.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx [hunk 3]
```diff
@@ -104,7 +107,6 @@ export const Palette = ({
   diagramElementId,
   targetObjectId,
   onDirectEditClick,
-  onEscape,
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: Is the property removed from `PaletteProps`?

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
Something somewhere in this PR is breaking the behavior of the palette in multiple use cases, I can't reopen a closed palette, some behavior like the delete is only working half the time.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx (hunk 2 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx]: I'm not sure it's comparable with the desktop version. Here when we open the palette we want to have the focus on the searchfield input and as such we can use direct edit only with F2 if the palette is opened.
If the palette is closed then F2 or typing can be used to start the direct edit.

Do you mean the direct-edit is starting when typing on the searchfield with the PR?

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx (hunk 1 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx]: If you open the palette you have the focus on the searchfield input and as such we want to keep the use of the `Delete `key to manipulate the text in the field.
You have to close the palette to Delete the element or click a tool.

**Comment by mcharfadi** [comment]
I made several changes to the PR :

- We can use direct edit or del key if the palette is opened but the input field is not focused (F2 work event if the input field is focused)
- The palette or one of the child element should always have the focus in order to be able to use the key event handler
- When clicking the arrow in the search field, we don't loose the focus anymore
- To use the del key you must not have the focus on the input field but you can click anywhere on the palette or press tab in order to delete the element

Also note that we have an issue with the tabindex of the quicktools that use the Tool.tsx component and as such pressing tab does not produce the expected result when selecting quicktools.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx [hunk 4]
```diff
@@ -78,9 +78,10 @@ export const useDiagramDelete = (): UseDiagramDeleteValue => {
 
   const onDelete = useCallback((event: React.KeyboardEvent<Element>) => {
     const { key } = event;
-    /*If a modifier key is hit alone, do nothing*/
     const isTextField = event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement;
-    if ((event.altKey && key === 'Alt') || (event.shiftKey && key === 'Shift') || isTextField) {
+
+    /*If a modifier key is hit alone, do nothing*/
+    if ((event.altKey && key === 'Alt') || (event.shiftKey && key === 'Shift') || isTextField || readOnly) {
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx]: Why are there changes related to the deletion of edges in this commit?

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.tsx [hunk 5]
```diff
@@ -94,14 +94,14 @@ export const MultiLabelEdge = memo(
...
         />
-        {selected ? (
-          <DiagramElementPalette
-            diagramElementId={id}
-            targetObjectId={data?.targetObjectId ?? ''}
-            labelId={label ? label.id : null}
-          />
-        ) : null}
         <EdgeLabelRenderer>
+          {selected ? (
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.tsx]: Why is there a change in the rendering of the palette of edges?

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx [hunk 6]
```diff
@@ -134,6 +136,41 @@ export const Palette = ({
...
 
+  const { hideDiagramPalette } = useDiagramPalette();
+  const { hideDiagramElementPalette } = useDiagramElementPalette();
+  const { hideGroupPalette } = useGroupPalette();
+
+  const closeAllPalettes = useCallback(() => {
+    hideDiagramPalette();
+    hideDiagramElementPalette();
+    hideGroupPalette();
+  }, [hideDiagramPalette, hideDiagramElementPalette, hideGroupPalette]);
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: Why should the child component of DiagramPalette knows about where it is being used? I don't understand the responsibilities and coupling being moved here.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
This commit is an unrelated set of changes without tests trading an unknown set of bugs for another. I'm not even sure what could be fixed or broken by this contribution.

What I do know is that with this I have a (new? different?) set of known bugs.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx (hunk 6 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: The events were there before we moved to the new palette.
They were moved because if the issue commented in `DiagramElementPalette.tsx`
```
    //If the Palette search field has the focus on, the useKeyPress from reactflow ignore the key pressed event.
    const onEscape = () => {
      hideDiagramElementPalette();
    };
```
    
Since the PR fixes the issue, we can move back the events in the Palette component were they are easier to handle.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.tsx (hunk 5 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/edge/MultiLabelEdge.tsx]: I don't think that the palette should not be a child of `<EdgeLabelRenderer>`
From my testing it was more efficient to put move it there, but since it's minor I can put it back there.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx (hunk 4 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx]: Since the PR fixes bug related to the deletion of edges and nodes when the palette is opened, I thought I would also add this quick fix (being able to delete a node if readonly is true & not being able to delete edges with this hook)
I can remove this change.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/search/PaletteSearchField.tsx [hunk 7]
```diff
@@ -47,26 +47,18 @@ export const PaletteSearchField = ({ onValueChanged, onEscape, onDirectEditClick
...
-  };
-
-  const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>): void => {
-    const { key } = event;
-    if (key === 'Escape' && onEscape) {
-      onEscape();
-    } else if (key === 'F2') {
-      onDirectEditClick();
-    }
+    document.getElementById('palette-search-field')?.focus();
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/search/PaletteSearchField.tsx]: Leverage useRef instead, this is more in line with the react way of doing things.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx [hunk 8]
```diff
@@ -82,11 +82,19 @@ export const PaletteToolList = ({ palette, onToolClick }: PaletteToolListProps)
...
 
   const listItemsRendered = palette.paletteEntries.flatMap((paletteEntry: GQLPaletteEntry) => {
     if (isSingleClickOnDiagramElementTool(paletteEntry)) {
-      return <ToolListItem onToolClick={onToolClick} tool={paletteEntry} key={'toolItem_' + paletteEntry.id} />;
+      return (
+        <ToolListItem
+          onToolClick={onToolClick}
+          tool={paletteEntry}
+          key={'toolItem_' + paletteEntry.id}
+          data-test-id={`paletteEntry-${paletteEntry.label}`}
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx]: `data-testid` not `data-test-id`

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx [hunk 9]
```diff
@@ -168,8 +168,10 @@ export const Palette = ({
         ref={nodeRef}
         className={classes.palette}
         data-testid="Palette"
+        id="palette"
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: Try no to use identifiers and build a proper API instead

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
I'll see if I can update the PR quickly

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx [hunk 10]
```diff
@@ -82,11 +82,19 @@ export const PaletteToolList = ({ palette, onToolClick }: PaletteToolListProps)
 
   const onBackToMainList = () => {
     setState((prevState) => ({ ...prevState, toolSection: null }));
+    document.getElementById('palette')?.focus();
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx]: Use a proper API, this child component here is knowing the internal structure of the parent component in which it is currently being used. We don't want this kind of coupling.

Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx]: If you are relying on an identifier in our dom code to do something, you are missing something in term of API or lifecycle. We don't need any id in our code to make it work. I would argue that relying on Reactflow ids may not be perfect too but that's another issue.

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/search/PaletteSearchField.tsx (hunk 7 above)
Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/search/PaletteSearchField.tsx]: Done

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx (hunk 9 above)
Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: Done

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx (hunk 10 above)
Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx]: Done

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx (hunk 8 above)
Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx]: Done

**Comment by sbegaudeau** [comment]
This should be the final rebase before the integration and release of 2025.1.7. I'll just check if everything is good on the update of the version for the newly integrated table projects.

**Review by sbegaudeau — APPROVED** [review]
