### PR TITLE
[2759] Reactivate the SelectionDialog

### LINKED ISSUE #2759: A tool cannot open a selection dialog in react flow
* [x] **I have specified the version** :
- latest (2023.12.0)

### Steps to reproduce

1. Open a flow model
2. Create a representation _Topography with auto layout_
3. On the _CompositeProcessor1_ palette's, trigger the tool _Processor with Connection_

### Expected behavior (SPROTTY)

selection_dialog_sprotty

### Actual behavior (REACT_FLOW)

selection_dialog_react_flow

### PR DESCRIPTION
**Pull request by florianbarbin**
# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?

- Import the Studio 
- [Studio.zip](https://github.com/user-attachments/files/16162153/Studio.zip)
- This studio is based on default one but with two additional tools:
  - One in the diagram palette which renamed the selected element
  - One on the Entity1 node that also open a selection dialog to rename the selected element
- Create a new project
- Create a new model based on the studio MM
- Create a new diagram 
- Create some element by using the node creation tools
- Use the selectionTool in the diagram contextual palette:
  - The selection dialog should be opened with all the model elements selectable
  - Select an element and perform finished
  - The element should be renamed
- Use the selection tool on an Entity1
- The selection dialog should only contain the selected element
- Select it and perform finish
- The element should be renamed

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties [hunk 1]
```diff
@@ -4,208 +4,214 @@
 # are made available under the terms of the Eclipse Public License v2.0
```
Comment (AxelRICHARD) [inline packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties]: Please double check this file to be sure that you have not introduced regression

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx [hunk 2]
```diff
@@ -412,6 +416,19 @@ export const Palette = ({
     [editingContextId, diagramId, collapseExpandMutation]
   );
 
+  const handleDialogDescription = (tool: GQLSingleClickOnDiagramElementTool, diagramElementTargetObjectId: string) => {
+    const onConfirm = (variables: GQLToolVariable[]) => {
+      invokeSingleClickTool(tool, variables);
+    };
+    showDialog(
+      'SELECTION_DIALOG_ID',
```
Comment (AxelRICHARD) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: It's strange here to use `SELECTION_DIALOG_ID` instead of the constant `SelectionDialog`. But it will introduce a dependency between diagram and selection.
So may be it means that there is something wrong here.
Unless I'm missing something, you should be able to use `dialogDescriptionId` from `GQLSingleClickOnDiagramElementTool`.

Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: Yes I am working on it but the problem is that the dialogDescriptionId is just an UUID so it does not contain the information about the type.
I started to modify the GraphQL API to have a "Dialog" field on the GQLSingleClickOnDiagramElementTool that will own that kind of information.

File: packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties (hunk 1 above)
Comment (florianbarbin) [reply packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties]: done. I don't know why the formatting is different on my env. I use the provided code formatting configuration

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.tsx [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+  const dialogComponentProps: DialogComponentProps = {
+    dialogDescriptionId: state.dialogDescriptionId ?? '',
+    editingContextId: state.editingContextId ?? '',
+    targetObjectId: state.targetObjectId ?? '',
+    onFinish,
+    onClose,
+  };
+  if (state.open && state.dialogTypeId) {
+    const dialogContribution: DiagramDialogContribution | undefined = dialogContributions.find((dialogContribution) =>
+      dialogContribution.canHandle(state.dialogTypeId as string)
```
Comment (AxelRICHARD) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.tsx]: may be `canHandle: (dialogTypeId : string)` could be `canHandle: (dialogTypeId : string | undefined)` in `diagramDialogExtensionPoint.types`, it would allows you to remove this unsafe cast

File: packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/ToolProvider.java [hunk 4]
```diff
@@ -234,18 +236,17 @@ private SingleClickOnDiagramElementTool convertNodeCreationDescription(Map<Strin
...
         List<IDiagramElementDescription> targetDescriptions = this.getParentNodeDescriptions(nodeCreationTool.getNodeMappings(), id2NodeDescriptions);
         var selectModelElementVariableOpt = new SelectModelElementVariableProvider().getSelectModelElementVariable(nodeCreationTool.getVariable());
-        String selectionDescriptionId = null;
-        if (selectModelElementVariableOpt.isPresent()) {
-            selectionDescriptionId = this.identifierProvider.getIdentifier(selectModelElementVariableOpt.get());
-        }
+        Dialog dialog = selectModelElementVariableOpt
+                .map(selectModelElementVariable -> new Dialog(this.identifierProvider.getIdentifier(selectModelElementVariable), SelectionDescription.TYPE))
+                .orElse(null);
         // @formatter:off
```
Comment (AxelRICHARD) [inline packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/ToolProvider.java]: Could you please remove all @formatter:off in all files you have edited, even if your code does not modify the lines were @formatter:off are?

File: CHANGELOG.adoc [hunk 5]
```diff
@@ -33,6 +33,35 @@ More existing APIs will be migrated to this new common pattern.
...
+```
+type SingleClickOnDiagramElementTool implements Tool {
+  id: ID!
+  label: String!
+  iconURL: [String!]!
+  appliesToDiagramRoot: Boolean!
+  dialog: Dialog
+  targetDescriptions: [DiagramElementDescription!]!
+}
+```
```
Comment (AxelRICHARD) [inline CHANGELOG.adoc]: There are lot of others breaking changes than the ones described here. Please add them.

File: packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx [hunk 6]
```diff
@@ -174,7 +176,7 @@ export const SelectionDialog = ({
             color="primary"
             onClick={() => {
               if (selectedObjectId) {
-                onFinish(selectedObjectId);
+                onFinish([{ name: 'selectedObject', value: selectedObjectId, type: GQLToolVariableType.objectId }]);
```
Comment (AxelRICHARD) [inline packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: It seems you create a new `GQLToolVariable ` with the `selectedObjectId` as value, but you name it `selectedObject`. Why you don't name it `selectedObjectId`?

Comment (florianbarbin) [reply packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: The "specifier" will manipulate the object (the variable value will be the object and not its id)

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.tsx (hunk 3 above)
Comment (AxelRICHARD) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.tsx]: Or manage the unsafe cast here, it will be better

File: packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx (hunk 6 above)
Comment (AxelRICHARD) [reply packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: So the "operation" that will transform an _objectId_ to an _object_ is done on the backend right?
So why you have to create a variable here, in the frontend?

Comment (florianbarbin) [reply packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: The idea is that the backend part does not make any assumptions on the variables provided by the frontend component. For now, we have identified 3 kinds of values which can be provided by a Dialog: An Object: in that case we use the Id. An array of objects or a simple string.

Comment (AxelRICHARD) [reply packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: I get that, but it still seems strange.
Here you set the variable _type_ to `GQLToolVariableType.objectId` which indicates that the variable will contain an _objectId_, but you set the variable _name_  to `selectedObject` which indicates that the variable will contain an _Object_

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.tsx (hunk 3 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.tsx]: done

File: packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/ToolProvider.java (hunk 4 above)
Comment (florianbarbin) [reply packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/services/diagrams/ToolProvider.java]: donne

File: packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx (hunk 6 above)
Comment (florianbarbin) [reply packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: The type represents a technical information to describe which kind of value is set.
We can change the variable type by object instead of objectId, in that case, it will represent the value type once converted by the backend side.

File: CHANGELOG.adoc [hunk 7]
```diff
@@ -33,6 +33,41 @@ More existing APIs will be migrated to this new common pattern.
...
+* The `String` attribute `org.eclipse.sirius.components.collaborative.diagrams.dto.InvokeSingleClickOnDiagramElementToolInput#selectedObjectId` has been replaced by the attribute `variables` of type `List<ToolVariable>`
+* The `String` attribute `org.eclipse.sirius.components.collaborative.diagrams.dto.SingleClickOnDiagramElementTool#selectionDescriptionId` has been replaced by the attribute `dialog` of type `Dialog`
+* The `String` attribute `org.eclipse.sirius.components.diagrams.tools.SingleClickOnDiagramElementTool` has been replaced by the attribute `dialog` of type `Dialog`
+* The `Palette` component in `sirius-components-diagrams` has a new property `diagramElementTargetObjectId` that represents the id of the diagram element target object.
+* The `DiagramPalette` component in `sirius-components-diagrams` has a new property `diagramTargetObjectId: string` that represents the diagram target object.
 === Dependency update
```
Comment (AxelRICHARD) [inline CHANGELOG.adoc:53]: Please let an empty line before the next section

Comment (florianbarbin) [reply CHANGELOG.adoc:53]: done

File: CHANGELOG.adoc [hunk 8]
```diff
@@ -33,6 +33,42 @@ More existing APIs will be migrated to this new common pattern.
...
+  representationId: ID!
+  variables: [ToolVariable!]!
+  diagramElementId: ID!
+  startingPositionX: Float!
+  startingPositionY: Float!
+  toolId: ID!
+}
+```
+
+ * The `SingleClickOnDiagramElementTool#dialogDescriptionId` has been replaced by a `dialog: Dialog` field to provide the information about the dialog that the frontend needs to retrieve in the extension point.
```
Comment (sbegaudeau) [inline CHANGELOG.adoc]: Why isn't that a XXXDescription? Could you please use something like `ToolDialogDescription` or `DiagramToolDialogDescription` in order not to use such a common name which may be used elsewhere in the future.

Why the need for a whole concept instead of of the identifier?

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls [hunk 9]
```diff
@@ -361,8 +364,12 @@ extend type Mutation {
   arrangeAll(input: ArrangeAllInput!): ArrangeAllPayload!
   deleteFromDiagram(input: DeleteFromDiagramInput!): DeleteFromDiagramPayload!
   editLabel(input: EditLabelInput!): EditLabelPayload!
-  invokeSingleClickOnDiagramElementTool(input: InvokeSingleClickOnDiagramElementToolInput!): InvokeSingleClickOnDiagramElementToolPayload!
-  invokeSingleClickOnTwoDiagramElementsTool(input: InvokeSingleClickOnTwoDiagramElementsToolInput!): InvokeSingleClickOnTwoDiagramElementsToolPayload!
+  invokeSingleClickOnDiagramElementTool(
+    input: InvokeSingleClickOnDiagramElementToolInput!
```
Comment (sbegaudeau) [inline packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls]: No need to change the formatting

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls [hunk 10]
```diff
@@ -361,8 +364,12 @@ extend type Mutation {
...
+  ): InvokeSingleClickOnDiagramElementToolPayload!
+  invokeSingleClickOnTwoDiagramElementsTool(
```
Comment (sbegaudeau) [inline packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls]: No need to change the formatting

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls [hunk 11]
```diff
@@ -286,10 +284,15 @@ type SingleClickOnDiagramElementTool implements Tool {
...
   iconURL: [String!]!
   appliesToDiagramRoot: Boolean!
-  selectionDescriptionId: String
+  dialog: Dialog
   targetDescriptions: [DiagramElementDescription!]!
 }
 
+type Dialog {
+  dialogDescriptionId: String!
+  dialogDescriptionType: String!
```
Comment (sbegaudeau) [inline packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls]: - This should be a XxxDescription or be removed entirely since I'm not sure why it needs to be a dedicated type?
- You could use `id` and `type`
- I'm not sure why this concept isn't an interface and why you need more than `id`?

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/Dialog.java [hunk 12]
```diff
@@ -0,0 +1,28 @@
...
+package org.eclipse.sirius.components.diagrams.tools;
+
+import java.util.Objects;
+
+/**
+ * Represents the Dialog type of the SingleClickOnDiagramElementTool#dialog attribute.
+ *
+ * @author fbarbin
+ */
+public record Dialog(String dialogDescriptionId, String dialogDescriptionType) {
```
Comment (sbegaudeau) [inline packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/Dialog.java]: This will have to be renamed not to use such a common concept name

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts [hunk 13]
```diff
@@ -0,0 +1,22 @@
...
+ *******************************************************************************/
+import { GQLToolVariable } from '../renderer/palette/Palette.types';
+export interface UseDialogValue {
+  showDialog: (
+    dialogTypeId: string,
+    editingContextID: string,
+    dialogDescriptionId: string,
+    targetObjectId: string,
+    onConfirm: (variables: GQLToolVariable[]) => void
+  ) => void;
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts]: I really don't understand this API.

- Why both a `diagramTypeId` and a `dialogDescriptionId` which are not even the same name as the GraphQL API
- `editingContextID` is not written this way, is that really necessary?
- Why give the targetObjectId?

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.tsx [hunk 14]
```diff
@@ -36,7 +36,13 @@ export const DiagramPalette = memo(({ diagramElementId }: DiagramPaletteProps) =
 
   return isOpened && x && y ? (
     <PalettePortal>
-      <Palette x={x} y={y} diagramElementId={diagramElementId} onDirectEditClick={() => {}} />
+      <Palette
+        x={x}
+        y={y}
+        diagramElementId={diagramElementId}
+        diagramElementTargetObjectId={diagramTargetObjectId}
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.tsx]: I don't understand why all this code has to be modified to give access to the `targetObjectId`...

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx [hunk 15]
```diff
@@ -412,6 +419,19 @@ export const Palette = ({
...
 
+  const handleDialogDescription = (tool: GQLSingleClickOnDiagramElementTool, diagramElementTargetObjectId: string) => {
+    const onConfirm = (variables: GQLToolVariable[]) => {
+      invokeSingleClickTool(tool, variables);
+    };
+    showDialog(
+      tool.dialog.dialogDescriptionType,
+      editingContextId,
+      tool.dialog.dialogDescriptionId,
+      diagramElementTargetObjectId,
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: Don't pass around the `targetObjectId` of the element on which the end user has clicked.

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts [hunk 16]
```diff
@@ -0,0 +1,26 @@
...
+  canHandle: (dialogTypeId: string) => boolean;
+  component: React.ComponentType<DialogComponentProps>;
+}
+
+export interface DialogComponentProps {
+  editingContextId: string;
+  dialogDescriptionId: string;
+  targetObjectId: string;
+  onClose: () => void;
+  onFinish: (variables: GQLToolVariable[]) => void;
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts]: I'm pretty sure that the `editingContextId` is  not needed and the `targetObjectId` too.

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts [hunk 17]
```diff
@@ -0,0 +1,26 @@
...
+ *
+ * SPDX-License-Identifier: EPL-2.0
+ *
+ * Contributors:
+ *     Obeo - initial API and implementation
+ *******************************************************************************/
+
+import { GQLToolVariable } from '../renderer/palette/Palette.types';
+export interface DiagramDialogContribution {
+  canHandle: (dialogTypeId: string) => boolean;
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts]: Why not use the descriptionId? Why have two pieces of information?

File: packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx [hunk 18]
```diff
@@ -71,13 +71,15 @@ const useSelectionObjectModalStyles = makeStyles((_theme) =>
...
+
 export const SelectionDialog = ({
   editingContextId,
-  selectionRepresentationId,
+  dialogDescriptionId,
   targetObjectId,
   onClose,
   onFinish,
-}: SelectionDialogProps) => {
+}: DialogComponentProps) => {
```
Comment (sbegaudeau) [inline packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: DialogComponentProps is too generic

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.types.ts [hunk 19]
```diff
@@ -73,7 +74,18 @@ export interface GQLInvokeSingleClickOnDiagramElementToolInput {
...
-  selectedObjectId: string | null;
+  variables: GQLToolVariable[];
+}
+export interface GQLToolVariable {
+  name: string;
+  value: string;
+  type: GQLToolVariableType;
+}
+
+export enum GQLToolVariableType {
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.types.ts]: Do not use enum in TypeScript, it creates a weird result, use an union instead: 

`export type GQLToolVariableType = 'STRING' | 'OBJECT_ID' | 'OBJECT_ID_ARRAY';

File: packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx (hunk 6 above)
Comment (sbegaudeau) [reply packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: > Here you set the variable type to GQLToolVariableType.objectId which indicates that the variable will contain an objectId, but you set the variable name to selectedObject which indicates that the variable will contain an Object

No that's not how we should think about this. As the contributor of a dialog, I want my dialog to be used to create a variable named `selectedObject`. To populate this variable, I'll give the backend some string as the value and it should be interpreted as the identifier of an object to resolve.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls (hunk 11 above)
Comment (florianbarbin) [reply packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls]: The id currently contains only an UUID that does not allow to identify the dialog type.
If we want to keep only an id, we need to modify the way we generate this id to own the dialog type information?

File: CHANGELOG.adoc (hunk 8 above)
Comment (florianbarbin) [reply CHANGELOG.adoc]: It idea was to own both the id and the information about the dialog type. We need to change the id to own the information about the dialog type if we want to keep only a dialogDescriptionId field?

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts (hunk 13 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts]: as discussed in the comments above, I am ok to remove the dialogType information if it can be owned by the dialogDescriptionID.
The TargetObjectId is needed by the selection dialog

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.tsx (hunk 14 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.tsx]: it is used to pass the information about the selected semantic element. Without this information, I can't retrieve it directly from org.eclipse.sirius.components.selection.graphql.datafetchers.subscription.SubscriptionSelectionEventDataFetcher

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts (hunk 17 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts]: The descriptionId is just an UUID

File: packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx (hunk 18 above)
Comment (florianbarbin) [reply packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: ok

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.types.ts (hunk 19 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.types.ts]: ok

File: CHANGELOG.adoc (hunk 8 above)
Comment (sbegaudeau) [reply CHANGELOG.adoc]: I still don't know why we would need both this two pieces of information. Why isn't an identifier enough?

Comment (florianbarbin) [reply CHANGELOG.adoc]: I am modifying the way we generate this identifier to have something similar to the other representation: siriusComponents://dialogDescription?kind=selectionDialogDescription etc"

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts (hunk 13 above)
Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts]: > The TargetObjectId is needed by the selection dialog

And the next dialog will ask for something else like the identifier of the node (instead of its semantic element), we won't change the API anytime a dialog needs something. The API should not depend on the specific needs of the selection dialog.

Why can't the selection dialog get the currently selected node from a react flow hook and find the targetObjectId on it directly or the current workbench selection from our `useSelection()` hook?

Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts]: > Why can't the selection dialog get the currently selected node from a react flow hook or the current workbench selection from our `useSelection()` hook?

I'm ok to use the hook. Are we sure that the selection cannot be changed in the meantime? (I don't see any particular scenario)

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls (hunk 11 above)
Comment (sbegaudeau) [reply packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls]: Ok so that's the limitation that I was missing. We should indeed change the way this identifier is computed. I don't even know how a simple UUID can be enough to open a dialog. For other description elements, the identifier has way more information. For example, the identifier of a node description is `siriusComponents://nodeDescription?sourceKind=view&sourceId=c5857f07-7382-3215-8c53-b690ca983655&sourceElementId=fe82e80e-7308-35a9-986d-f010401063ee`.

So, for a selection dialog, having an identifier like this would be necessary:

```
siriusComponents://selectionDialogDescription?sourceKind=view&sourceId=XXX&sourceElementId=XXXX
```

I don't know how we could retrieve the proper Dialog object otherwise since we don't know the id of its view model.

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts (hunk 17 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts]: removed and replaced by the descriptionId that now contains the type information.

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts (hunk 16 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts]: done, replaced by the useDialog hook to retrieve the editingContext from the DialogContext

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx (hunk 15 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/Palette.tsx]: done

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.tsx (hunk 14 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/DiagramPalette.tsx]: done

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts (hunk 13 above)
Comment (florianbarbin) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/useDialog.types.ts]: done

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/Dialog.java (hunk 12 above)
Comment (florianbarbin) [reply packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/tools/Dialog.java]: removed

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls (hunk 11 above)
Comment (florianbarbin) [reply packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls]: done

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls (hunk 10 above)
Comment (florianbarbin) [reply packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls]: done

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls (hunk 9 above)
Comment (florianbarbin) [reply packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/resources/schema/diagram.graphqls]: done

File: CHANGELOG.adoc (hunk 8 above)
Comment (florianbarbin) [reply CHANGELOG.adoc]: done

**Comment by AxelRICHARD** [comment]
Please squash the commits before the merge

File: packages/selection/backend/sirius-components-collaborative-selection/src/main/java/org/eclipse/sirius/components/collaborative/selection/SelectionEventProcessor.java [hunk 20]
```diff
@@ -133,7 +133,14 @@ private IRepresentationRefreshPolicy getDefaultRefreshPolicy() {
     private Selection refreshSelection() {
         VariableManager variableManager = new VariableManager();
         var optionalObject = this.objectService.getObject(this.editingContext, this.objectId);
-        variableManager.put(VariableManager.SELF, optionalObject.orElse(null));
+
+        //The provided Object ID can represent the Diagram if the the tool has been invoked on the diagram background.
```
Comment (sbegaudeau) [inline packages/selection/backend/sirius-components-collaborative-selection/src/main/java/org/eclipse/sirius/components/collaborative/selection/SelectionEventProcessor.java]: Self in a tool executed in the background of a diagram is never the diagram itself, you may have the wrong object id here

File: packages/selection/frontend/sirius-components-selection/package.json [hunk 21]
```diff
@@ -32,6 +32,7 @@
   "peerDependencies": {
     "@apollo/client": "3.10.4",
     "@eclipse-sirius/sirius-components-core": "*",
+    "@eclipse-sirius/sirius-components-diagrams": "*",
```
Comment (sbegaudeau) [inline packages/selection/frontend/sirius-components-selection/package.json:35]: I'm not sure why selection needs to depend on diagrams now...

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts [hunk 22]
```diff
@@ -0,0 +1,24 @@
...
+ * https://www.eclipse.org/legal/epl-2.0/
+ *
+ * SPDX-License-Identifier: EPL-2.0
+ *
+ * Contributors:
+ *     Obeo - initial API and implementation
+ *******************************************************************************/
+
+import { GQLToolVariable } from '../renderer/palette/Palette.types';
+export interface DiagramDialogContribution {
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts]: new line after the import

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.ts [hunk 23]
```diff
@@ -0,0 +1,19 @@
...
+ *
+ * SPDX-License-Identifier: EPL-2.0
+ *
+ * Contributors:
+ *     Obeo - initial API and implementation
+ *******************************************************************************/
+import { DataExtensionPoint } from '@eclipse-sirius/sirius-components-core';
+import { DiagramDialogContribution } from './diagramDialogExtensionPoint.types';
+
+export const diagramDialogContributionExtensionPoint: DataExtensionPoint<Array<DiagramDialogContribution>> = {
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.ts]: Update the filename to match the naming conventions of other extension points

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.types.ts [hunk 24]
```diff
@@ -0,0 +1,30 @@
...
+ * SPDX-License-Identifier: EPL-2.0
+ *
+ * Contributors:
+ *     Obeo - initial API and implementation
+ *******************************************************************************/
+
+import { GQLToolVariable } from '../renderer/palette/Palette.types';
+
+export interface DialogContextValue {
+  currentEditingContextId: string | undefined;
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.types.ts]: Why this `currentEditingContextId` and why can it be `undefined`? even `null` would be very odd

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.types.ts [hunk 25]
```diff
@@ -0,0 +1,30 @@
...
+  showDialog: (
+    editingContextId: string,
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.types.ts]: Do we really need to give the `editingContextId`?

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.types.ts [hunk 26]
```diff
@@ -0,0 +1,30 @@
...
+    dialogDescriptionId: string,
+    onConfirm: (variables: GQLToolVariable[]) => void
+  ) => void;
+}
+
+export interface DialogContextProviderState {
+  open: boolean;
+  editingContextId: string | undefined;
+  dialogDescriptionId: string | undefined;
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.types.ts]: Why those `undefined` values? I'll need to investigate that

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/ToolVariable.java [hunk 27]
```diff
@@ -0,0 +1,21 @@
...
+ * SPDX-License-Identifier: EPL-2.0
+ *
+ * Contributors:
+ *     Obeo - initial API and implementation
+ *******************************************************************************/
+package org.eclipse.sirius.components.collaborative.diagrams.dto;
+
+/**
+ * Represents a ToolVariable entry.
+ * @author fbarbin
```
Comment (sbegaudeau) [inline packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/ToolVariable.java:18]: Missing new line

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandler.java [hunk 28]
```diff
@@ -149,24 +144,47 @@ private IStatus executeTool(IEditingContext editingContext, IDiagramContext diag
...
             }
         }
         return result;
     }
 
+    private void handleDialogVariables(IEditingContext editingContext, VariableManager variableManager, List<ToolVariable> variables) {
+        variables.forEach(toolVariable -> {
+            this.handleToolVariable(toolVariable, editingContext, variableManager);
+        });
+    }
```
Comment (sbegaudeau) [inline packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandler.java]: No need for a method to perform a single `forEach`

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.tsx [hunk 29]
```diff
@@ -0,0 +1,75 @@
...
+  const onFinish = (toolVariables: GQLToolVariable[]) => {
+    state.onConfirm(toolVariables);
+    setState((prevState) => ({ ...prevState, open: false, dialogTypeId: undefined }));
+  };
+
+  const onClose = () => {
+    setState((prevState) => ({ ...prevState, open: false, dialogTypeId: undefined }));
+  };
+
+  let DialogComponent: React.ComponentType<DiagramDialogComponentProps> | undefined;
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.tsx]: Always prefer `null` to `undefined` especially in order to explicitly indicate that something is missing

File: packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx [hunk 30]
```diff
@@ -71,18 +71,17 @@ const useSelectionObjectModalStyles = makeStyles((_theme) =>
...
+
+export const SelectionDialog = ({ dialogDescriptionId, onClose, onFinish }: DiagramDialogComponentProps) => {
   const classes = useSelectionObjectModalStyles();
 
   const [{ value, context }, dispatch] = useMachine<SelectionDialogContext, SelectionDialogEvent>(
     selectionDialogMachine
   );
+  const { selection: currentSelection } = useSelection();
+  const { currentEditingContextId: editingContextId } = useDialog();
+  const targetObjectId = currentSelection.entries.length > 0 ? currentSelection?.entries[0]?.id : '';
```
Comment (sbegaudeau) [inline packages/selection/frontend/sirius-components-selection/src/SelectionDialog.tsx]: Nothing indicates that the dialog should be opened using the current selection. This must be where this invalid value for `SELF` is coming from.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/selection/SelectionControllerIntegrationTests.java [hunk 31]
```diff
@@ -93,6 +97,12 @@ subscription selectionEvent($input: SelectionEventInput!) {
     @Autowired
     private EditTextfieldMutationRunner editTextfieldMutationRunner;
 
+    @Autowired
+    private ModelOperationDiagramDescriptionProvider modelOperationDiagramDescriptionProvider;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/selection/SelectionControllerIntegrationTests.java:101]: Keep example dedicated to their test suite, don't just start picking one at random to change its behavior. I don't want to start seeing coupling being introduced between test suite.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ModelOperationDiagramDescriptionProvider.java [hunk 32]
```diff
@@ -61,6 +62,8 @@ public class ModelOperationDiagramDescriptionProvider implements IEditingContext
 
     private NodeTool createNodeTool;
 
+    private NodeTool renameNodeTool;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/ModelOperationDiagramDescriptionProvider.java:65]: A dedicated example should be created instead of just taking one to change the scope of its behavior

File: packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties [hunk 33]
```diff
@@ -10,205 +10,211 @@
...
-pluginName=Diagram Edit Support
-providerName=www.example.org
-_UI_CreateChild_text={0}
-_UI_CreateChild_text2={1} {0}
-_UI_CreateChild_text3={1}
-_UI_CreateChild_tooltip=Create New {0} Under {1} Feature
-_UI_CreateChild_description=Create a new child of type {0} for the {1} feature of the selected {2}.
-_UI_CreateSibling_description=Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.
-_UI_PropertyDescriptor_description=The {0} of the {1}
+pluginName = Diagram Edit Support
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties:13]: Why such a change in formatting modifying pretty much every single line?

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/IDiagramIdProvider.java [hunk 34]
```diff
@@ -24,17 +25,20 @@
  */
 public interface IDiagramIdProvider extends IRepresentationDescriptionIdProvider<DiagramDescription> {
 
+
     String DIAGRAM_DESCRIPTION_KIND = PREFIX + "?kind=diagramDescription";
 
-    String NODE_DESCRIPTION_KIND = "siriusComponents://nodeDescription";
+    String NODE_DESCRIPTION_KIND = SCHEMA_PREFIX + "nodeDescription";
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/IDiagramIdProvider.java]: Don't start creating abstractions for this kind of operations, it was way more readable and understandable before and it did not create any issue in term of maintainability.

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IRepresentationDescriptionIdProvider.java [hunk 35]
```diff
@@ -19,11 +19,14 @@
...
- * @param <T> The type of representation description supported.
+ * @param <T>
+ *            The type of representation description supported.
  */
 public interface IRepresentationDescriptionIdProvider<T extends RepresentationDescription> {
 
-    String PREFIX = "siriusComponents://representationDescription";
+    String SCHEMA_PREFIX = "siriusComponents://";
+
+    String PREFIX = SCHEMA_PREFIX + "representationDescription";
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IRepresentationDescriptionIdProvider.java]: Don't change that, it does not solve any issue worth the lack of readability it introduces. Fighting duplicate code at all cost by creating abstractions and coupling at all cost is not worth it.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ModelOperationDiagramControllerTests.java [hunk 36]
```diff
@@ -130,4 +129,48 @@ public void givenDiagramWhenToolWithComplexModelOperationsIsExecutedThenItWorksA
                 .thenCancel()
                 .verify(Duration.ofSeconds(10));
     }
+
+    @Test
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/ModelOperationDiagramControllerTests.java:133]: Can be moved to a dedicated test suite

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
I'll have to review some details while running the code and I'll fix the last small issue remaining to merge it

File: packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties (hunk 33 above)
Comment (sbegaudeau) [reply packages/view/backend/sirius-components-view-diagram-edit/src/main/resources/plugin.properties:13]: Done

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/IDiagramIdProvider.java (hunk 34 above)
Comment (sbegaudeau) [reply packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/IDiagramIdProvider.java]: Done

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IRepresentationDescriptionIdProvider.java (hunk 35 above)
Comment (sbegaudeau) [reply packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IRepresentationDescriptionIdProvider.java]: Done

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandler.java (hunk 28 above)
Comment (sbegaudeau) [reply packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/handlers/InvokeSingleClickOnDiagramElementToolEventHandler.java]: Done

File: packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/ToolVariable.java (hunk 27 above)
Comment (sbegaudeau) [reply packages/diagrams/backend/sirius-components-collaborative-diagrams/src/main/java/org/eclipse/sirius/components/collaborative/diagrams/dto/ToolVariable.java:18]: Done

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.types.ts (hunk 26 above)
Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/DialogContext.types.ts:28]: Done

File: packages/selection/backend/sirius-components-collaborative-selection/src/main/java/org/eclipse/sirius/components/collaborative/selection/SelectionEventProcessor.java (hunk 20 above)
Comment (sbegaudeau) [reply packages/selection/backend/sirius-components-collaborative-selection/src/main/java/org/eclipse/sirius/components/collaborative/selection/SelectionEventProcessor.java]: Done

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.ts (hunk 23 above)
Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.ts]: Done

File: packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts (hunk 22 above)
Comment (sbegaudeau) [reply packages/diagrams/frontend/sirius-components-diagrams/src/dialog/diagramDialogExtensionPoint.types.ts]: Done

File: packages/selection/backend/sirius-components-collaborative-selection/src/main/java/org/eclipse/sirius/components/collaborative/selection/SelectionEventProcessor.java (hunk 20 above)
Comment (sbegaudeau) [reply packages/selection/backend/sirius-components-collaborative-selection/src/main/java/org/eclipse/sirius/components/collaborative/selection/SelectionEventProcessor.java]: Done, this will have to be fixed in the frontend

Comment (sbegaudeau) [reply packages/selection/backend/sirius-components-collaborative-selection/src/main/java/org/eclipse/sirius/components/collaborative/selection/SelectionEventProcessor.java]: Done

File: packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/SelectionDialogDescriptionItemProvider.java [hunk 37]
```diff
@@ -85,19 +76,19 @@ protected void addSelectionCandidatesExpressionPropertyDescriptor(Object object)
...
     /**
-     * This returns SelectionDescription.gif. <!-- begin-user-doc --> <!-- end-user-doc -->
+     * This returns SelectionDialogDescription.gif. <!-- begin-user-doc --> <!-- end-user-doc -->
      *
      * @generated
      */
     @Override
     public Object getImage(Object object) {
-        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/SelectionDescription"));
+        return this.overlayImage(object, this.getResourceLocator().getImage("full/obj16/SelectionDialogDescription"));
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-diagram-edit/src/main/java/org/eclipse/sirius/components/view/diagram/provider/SelectionDialogDescriptionItemProvider.java:91]: I've spent way too much time figuring out that this was invalid and to remember that it was necessary to change that in order to make it work. Did anyone succeed in executing fully this contribution?

**Comment by sbegaudeau** [comment]
So now things are working as expected but I still have two elements to review and possibly modify (the dependency to sirius-components-diagrams and the tests)

**Comment by sbegaudeau** [comment]
I've reduced the dependency to `sirius-components-diagrams` as much as possible but it will still remain for now since the impact is minimal, we will just have to ensure that it does not grow over time.

/cc @florianbarbin When we will work on the support for dialogs in the explorer, we will have to move DialogDescription in view.ecore (from diagram.ecore now), rename `DiagramDialogComponentProps` to `DialogComponentProps ` and move it to `sirius-components-core`.


Let's not add more dependencies to `sirius-components-diagrams` in `sirius-components-selection`.

**Review by sbegaudeau — APPROVED** [review]

**Comment by sbegaudeau** [comment]
Some tests will have to be moved later
