### PR TITLE
[2460] Separates the management of element creation from the reference widget in specific services

### LINKED ISSUE #2460: Invalid ChildCreationDescription returned while creating new a instance from a Reference widget
While creating a new instance using the "+" button from Reference Widget that represents a containment reference the presented candidates are incorrect. The creation description should be limited to the reference being edited. In the current implementation it return all pair of <ERefence,EClass> that match the criteria <ParentType,ChildType> whereas it should take into account the current containment reference.

Using the following meta model:

image

It easy to reproduce a case where we can create "Entity one in refC1" while editing the reference "Refc2".

image

Causing the weird behavior:

BugREferenceWidgetWrongCandidateCreation

To reproduce:

[InstanceProblem.zip](https://github.com/eclipse-sirius/sirius-web/files/12857767/InstanceProblem.zip)
[Studio.zip](https://github.com/eclipse-sirius/sirius-web/files/12857768/Studio.zip)

### PR DESCRIPTION
**Pull request by frouene**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/2460

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Comment by frouene** [comment]
This PR doesn't correct the issue #2460 but it's a first step to facilitate the widget reference configuration.

File: packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/CreateElementEventHandler.java [hunk 1]
```diff
@@ -87,8 +95,14 @@ public void handle(One<IPayload> payloadSink, Many<ChangeDescription> changeDesc
             if (optionalWidget.isPresent() && optionalWidget.get().isReadOnly()) {
                 payload = new ErrorPayload(input.id(), this.messageService.unableToEditReadOnlyWidget());
             } else {
-                var handlerInput = this.getHandlerInput(editingContext, input);
-                Optional<Object> optionalObject = optionalWidget.map(ReferenceWidget::getCreateElementHandler).map(handler -> handler.apply(handlerInput));
+                Optional<Object> optionalObject = this.referenceWidgetCreateElementHandlers.stream()
+                        .filter(provider -> provider.canHandle(input.descriptionId()))
+                        .findFirst()
```
Comment (pcdavid) [inline packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/CreateElementEventHandler.java:100]: The default `ReferenceWidgetDefaultCreateElementHandler` will always return `true` to `canHandle`. How can we be sure it's not the one we get here instead of another, application-provided one?

File: packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ReferenceWidgetChildCreationDescriptionsEventHandler.java [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+    @Override
+    public void handle(Sinks.One<IPayload> payloadSink, Sinks.Many<ChangeDescription> changeDescriptionSink, IEditingContext editingContext, IInput input) {
+        this.counter.increment();
+
+        List<ChildCreationDescription> childCreationDescriptions = List.of();
+        if (input instanceof ReferenceWidgetChildCreationDescriptionsInput castInput) {
+
+            childCreationDescriptions = this.referenceWidgetCreateElementHandlers.stream()
+                    .filter(provider -> provider.canHandle(castInput.descriptionId()))
+                    .findFirst()
```
Comment (pcdavid) [inline packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ReferenceWidgetChildCreationDescriptionsEventHandler.java:69]: Same remark.

File: packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ReferenceWidgetRootCreationDescriptionsEventHandler.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+    @Override
+    public void handle(Sinks.One<IPayload> payloadSink, Sinks.Many<ChangeDescription> changeDescriptionSink, IEditingContext editingContext, IInput input) {
+        this.counter.increment();
+
+        List<ChildCreationDescription> childCreationDescriptions = List.of();
+        if (input instanceof ReferenceWidgetRootCreationDescriptionsInput castInput) {
+
+            childCreationDescriptions = this.referenceWidgetCreateElementHandlers.stream()
+                    .filter(provider -> provider.canHandle(castInput.descriptionId()))
+                    .findFirst()
```
Comment (pcdavid) [inline packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/ReferenceWidgetRootCreationDescriptionsEventHandler.java:68]: Same remark.

**Review by pcdavid — CHANGES_REQUESTED** [review]

File: packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/CreateElementEventHandler.java (hunk 1 above)
Comment (frouene) [reply packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/handlers/CreateElementEventHandler.java:100]: I changed the approch, now I explicitly call this service when no other canHandle is true.
This way, an application that wants to provide its own handler, doesn't need to play with spring annotation `@Order`

**Review by pcdavid — APPROVED** [review]
I find it strange to keep both `ReferenceWidgetDefaultCreateElementHandler` and `ReferenceWidgetDefaultCandidateSearchProvider` as Spring Boot `@Services`.

This means they will always appear in e.g. `List<IReferenceWidgetRootCandidateSearchProvider>` so they need to return `false` on `canHandle` (which seems _wrong_ as they actually can handle all `descriptionId`), and *then* we also inject them through they concrete type to use them as fallbacks/actual defaults.

IMO they should not be `@Services`, declare they `canHandle` all cases (which is the case), and be created explicitly where needed (`ReferenceWidgetDefaultCandidateSearchProvider` has no constructor dependency, `ReferenceWidgetDefaultCreateElementHandler` only needs the `IEditService`, which we have or can get everywhere we explicitly need to build a `ReferenceWidgetDefaultCreateElementHandler`).

Still approving so that this can be merged, as the current solution works in practice, but I'll try to propose a separate PR with the approach outlined above.

**Comment by pcdavid** [comment]
See https://github.com/eclipse-sirius/sirius-web/pull/2518 for a followup corresponding to my previous comment.
