### PR TITLE
[5240] Ensure semantic data doesn't contain proxies after library update

### LINKED ISSUE #5240: Updating a library should not persist proxies in the database
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
- other: please specify
* [x] **I have specified my environment** : 
- All

### Steps to reproduce

Create a project and import a library.
Create an element with a non-containment reference to an object of this library.
Update the library with a version that does not contain the targeted object

### Expected behavior

The project's semantic data does not contain proxies

### Actual behavior

The project's semantic data contains unresolvable proxies.
This breaks a core contract of Sirius Web (we do not persist documents that contain unresolvable proxies).

### PR DESCRIPTION
**Pull request by gdaniel**
Fixes #5240 

Bug: https://github.com/eclipse-sirius/sirius-web/issues/5240

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?

Create a papaya project
Import papaya-java@0.0.3
Create an interface "Interface1"
Create an interface "Interface2"
Update "Interface2" to make it extend "Interface1" and "java.time.temporal.Temporal"
Update papaya-java to 0.0.1 (this version does not contain the `Temporal` interface)
Check that "Interface2" now extends "Interface1" and nothing else

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-tests-data/src/main/resources/sirius-web-scripts/papaya-library.sql [hunk 1]
```diff
@@ -572,4 +572,92 @@ INSERT INTO library (
   'The Sirius Web Tests Data library',
   '2025-03-14 12:25:11.524',
   '2025-03-14 12:25:11.524'
+);
+
+INSERT INTO semantic_data (
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-tests-data/src/main/resources/sirius-web-scripts/papaya-library.sql:577]: I added a new version of the library without the annotation to be able to trigger an update that could generate proxies.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/libraries/LibraryControllerIntegrationTests.java [hunk 2]
```diff
@@ -174,12 +193,15 @@ public void givenProjectWithDependenciesWhenDependencyIsUpdatedThenEditingContex
         Optional<Library> optionalLibrary = this.librarySearchService.findByNamespaceAndNameAndVersion("papaya", "sirius-web-tests-data", "2.0.0");
         assertThat(optionalLibrary).isPresent();
 
+        var editingContextEventInput = new EditingContextEventInput(UUID.randomUUID(), PapayaIdentifiers.PAPAYA_EDITING_CONTEXT_ID.toString());
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/libraries/LibraryControllerIntegrationTests.java:196]: Based on a discussion we had some time ago I updated this test to use a subscription to the editing context. I did the same for the new test I contributed.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/UpdateLibraryEventHandler.java [hunk 3]
```diff
@@ -122,6 +126,11 @@ public void handle(One<IPayload> payloadSink, Many<ChangeDescription> changeDesc
 
                         this.editingContextDependencyLoader.loadDependencies(siriusWebEditingContext);
 
+                        long start = System.nanoTime();
+                        this.removeUnresolvedProxies(siriusWebEditingContext.getDomain().getResourceSet());
+                        Duration timeToRemoveProxies = Duration.ofNanos(System.nanoTime() - start);
+                        this.logger.trace("Removed proxies in {}ms", timeToRemoveProxies.toMillis());
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/UpdateLibraryEventHandler.java:132]: I used the same log as in `DocumentSanitizedJsonContentProvider`.
Proxy resolution could become a bottleneck in some use cases, this log could help to identify the issue.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/UpdateLibraryEventHandler.java [hunk 4]
```diff
@@ -200,4 +209,25 @@ private void removeLibraryDependency(UpdateLibraryInput updateLibraryInput, Edit
                 this.semanticDataUpdateService.removeDependencies(updateLibraryInput, AggregateReference.to(semanticData.getId()), List.of(library.getSemanticData()));
             });
     }
+
+    private void removeUnresolvedProxies(ResourceSet resourceSet) {
+        List<Resource> nonLibraryResources = resourceSet.getResources().stream()
+                .filter(resource -> resource.eAdapters().stream()
+                        .noneMatch(LibraryMetadataAdapter.class::isInstance))
+                .toList();
+        // Only look for proxies in Resources that are persisted in the project's semantic data
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/UpdateLibraryEventHandler.java:218]: As we discussed some time ago, updating a single library could have side effects on other imported libraries, such as breaking cross-library references.
Since we do not persist the resources of imported libraries I don't think it is the responsibility of this class to ensure they do not contain proxies (I don't even know if it is a bad thing per se). Looking only at resources owned by the project is also a nice way to reduce the overhead to retrieve the proxies to delete.

In addition, if updating a library deletes proxies in other libraries, we will have an inconsistent behavior between how the editing context is loaded and how it is modified by an update.
For the record, at the moment it is possible to have proxies in resources loaded from libraries if the dependency resolution overrides transitive dependencies. 

I think this question should be part of a broader work to better specify how we manage complex library updates.

**Review by sbegaudeau — APPROVED** [review]
