### PR TITLE
[4875] Improve table representation lifecycle

### LINKED ISSUE #4875: Table sometimes lead to blank content and require a navigator refresh
### Screenshots

Image

### Steps to reproduce

* Create a "Papaya package Table" on a package with some content
* Add an object in Package via Model Explorer (which should lead to a refresh of the table)
Current: KO-> the table is not refreshed
Expected: the table should be refreshed
* Try to change the order of two columns
Current: KO-> the table gets blank
Expected: the columns should be reorder

Note: This scenario is given as example, but the issue is not systematically reproducible.

Leads to try to reproduce:
* create the table while any other representation is opened
* create the table while the project has just been opened

Edit 20250428
I have now a reproducible scenario
* Create a "Papaya package Table" on a package with some content
* Reload the page
* wait few seconds
* KO -> the blank page is displayed

### PR DESCRIPTION
**Pull request by frouene**
# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/TableSuccessPayload.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+import java.util.Objects;
+import java.util.UUID;
+
+import org.eclipse.sirius.components.core.api.IPayload;
+import org.eclipse.sirius.components.tables.Table;
+
+/**
+ * @author frouene
+ */
+public record TableSuccessPayload(UUID id, Table table) implements IPayload {
```
Comment (lfasani) [inline packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/TableSuccessPayload.java]: I had rather focus on the useful metadata of the Table and not the whole table.
TableSuccessPayload -> TableMetaDataSuccessPayload or TableConfigurationSuccessPayload
`TableMetaDataSuccessPayload(UUID id, String globalFilter, List<ColumnFilter> columnFilters, List<ColumnSort> columnSort)`

File: packages/tables/frontend/sirius-components-tables/src/rows/filters/useTableRowFilters.ts [hunk 2]
```diff
@@ -43,16 +43,21 @@ const getAllTableRowFiltersQuery = gql`
...
+): UseTableRowFilterValue => {
   const [state, setState] = useState<UseTableRowFilterState>({ rowFilters: [], activeRowFilterIds: [] });
   const { loading, data, error } = useQuery<GQLGetAllTableRowFiltersData, GQLGetAllTableRowFiltersVariables>(
     getAllTableRowFiltersQuery,
     {
       variables: {
         editingContextId,
-        representationId: tableId,
-        tableId,
+        representationId: representationId ?? '',
```
Comment (lfasani) [inline packages/tables/frontend/sirius-components-tables/src/rows/filters/useTableRowFilters.ts:57]: It is useless to do the query if representationId is null
Better to change the skip condition adding `skip: table === null && representationId `

Comment (frouene) [reply packages/tables/frontend/sirius-components-tables/src/rows/filters/useTableRowFilters.ts:57]: The skip condition make it impossible to make the query with a representationId null.
However, typescript forces us to take into account this case.

File: packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/TableSuccessPayload.java (hunk 1 above)
Comment (frouene) [reply packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/TableSuccessPayload.java]: I changed this PR in this direction

File: packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls [hunk 3]
```diff
@@ -40,6 +40,16 @@ type ColumnSort {
   desc: Boolean!
 }
 
+extend type RepresentationMetadata {
+  configuration: TableConfiguration
+}
+type TableConfiguration {
```
Comment (sbegaudeau) [inline packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls:47]: newline

File: packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/query/EditingContextTableDataFetcher.java [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+import graphql.schema.DataFetchingEnvironment;
+import reactor.core.publisher.Mono;
+
+/**
+ * Data fetcher used to retrieve table configuration.
+ *
+ * @author frouene
+ */
+@QueryDataFetcher(type = "RepresentationMetadata", field = "configuration")
+public class EditingContextTableDataFetcher implements IDataFetcherWithFieldCoordinates<CompletableFuture<TableConfiguration>> {
```
Comment (sbegaudeau) [inline packages/tables/backend/sirius-components-tables-graphql/src/main/java/org/eclipse/sirius/components/tables/graphql/datafetchers/query/EditingContextTableDataFetcher.java]: Update the name of the datafetcher to match the name of the type and field

File: packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/TableConfigurationInput.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+ * The input of the table configuration query.
+ *
+ * @author frouene
+ */
+public record TableConfigurationInput(UUID id, String editingContextId, String tableId) implements ITableInput {
+
+    @Override
+    public String tableId() {
+        return this.tableId;
+    }
```
Comment (sbegaudeau) [inline packages/tables/backend/sirius-components-collaborative-tables/src/main/java/org/eclipse/sirius/components/collaborative/tables/dto/TableConfigurationInput.java]: Is that necessary? (same comment for the id accessor)

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

**Review by sbegaudeau — APPROVED** [review]
This seems good, I'll just perform some additional checks before merging it
