### PR TITLE
[4967] Fix representation creation when importing/uploading whole projects

### LINKED ISSUE #4967: Uploading a project fails to re-create the exported representations
## Steps to reproduce

1. Use Sirius Web 2025.4.2 or later (this regression was introduced with the switch to Sirius EMF JSON 2.25.0).
2. Create a new "Flow" project from the default template on the main page.
3. The newly created project has a _Topography_ diagram created on the top-level NewSystem element.
4. In the project menu, select "Download". You'll get a `Flow.zip` file.
5. Go back to the project browser, and select _Upload project_. Choose the `Flow.zip` local file you got from the previous step.
6. In the newly created project, the expected semantic data is there, but the _Topography_ diagram has not been re-created.

### PR DESCRIPTION
**Pull request by pcdavid**
Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentSuccessPayload.java [hunk 1]
```diff
@@ -23,5 +24,5 @@
  *
  * @author sbegaudeau
  */
-public record UploadDocumentSuccessPayload(@NotNull UUID id, @NotNull DocumentDTO document, String report) implements IPayload {
+public record UploadDocumentSuccessPayload(@NotNull UUID id, @NotNull DocumentDTO document, String report, Map<String, String> idMapping) implements IPayload {
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentSuccessPayload.java:30]: This is returned to the frontend, it's quite odd to expose this information here. I'll see if we really need this part.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java [hunk 2]
```diff
@@ -164,9 +175,7 @@ private Optional<Resource> getResource(ResourceSet resourceSet, URI resourceURI,
             this.logger.warn(exception.getMessage(), exception);
         }
         byte[] bytes = baos.toByteArray();
-        return this.externalResourceLoaderServices.stream()
-                .filter(loader -> loader.canHandle(new ByteArrayInputStream(bytes), resourceURI, resourceSet))
-                .findFirst()
+        return this.externalResourceLoaderServices.stream().filter(loader -> loader.canHandle(new ByteArrayInputStream(bytes), resourceURI, resourceSet)).findFirst()
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java]: The formatting was more readable before

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IDocumentSanitizedJsonContentProvider.java [hunk 3]
```diff
@@ -23,6 +24,13 @@
  * @author sbegaudeau
  */
 public interface IDocumentSanitizedJsonContentProvider {
+    /**
+     * The result of sanitizing a document.
+     *
+     * @author pcdavid
+     */
+    record SanitizedResult(String content, Map<String, String> idMapping) {
+    }
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IDocumentSanitizedJsonContentProvider.java]: This record can have its own file

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IUploadFileLoader.java [hunk 4]
```diff
@@ -24,7 +26,13 @@
  * @author frouene
  */
 public interface IUploadFileLoader {
+    /**
+     * The result of uploading a new file.
+     *
+     * @author pcdavid
+     */
+    record UploadedResource(Resource resource, Map<String, String> idMapping) { }
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/api/IUploadFileLoader.java]: Same comment

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentSuccessPayload.java (hunk 1 above)
Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentSuccessPayload.java:30]: After a review of the code it seems that it's the easiest way to achieve our goal. I'll add a small note here to indicate that we should probably consider removing this when we will improve the upload process which is a bit odd right now.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

**Review by sbegaudeau — APPROVED** [review]
I've rebased the code and fix the minor comments. I'll wait for the build and merge it.
