### PR TITLE
[4825] Add tooltip support for table cells

### LINKED ISSUE #4825: The tooltip is not displayed in table cell
### Steps to reproduce

* have a view model with a cell with a TooltipExpression
* create the table
* hover the mouse on the cell

### Expected behavior

the tooltip should be displayed

### Actual behavior

the tooltip is not displayed

### PR DESCRIPTION
**Pull request by frouene**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/4825

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/descriptions/IconLabelCellDescription.java [hunk 1]
```diff
@@ -42,6 +42,8 @@ public final class IconLabelCellDescription implements ICellDescription {
 
     private BiFunction<VariableManager, Object, List<String>> cellIconURLsProvider;
 
+    private BiFunction<VariableManager, Object, String> cellTooltipValueProvider;
```
Comment (sbegaudeau) [inline packages/tables/backend/sirius-components-tables/src/main/java/org/eclipse/sirius/components/tables/descriptions/IconLabelCellDescription.java:45]: It's quite odd that this provider takes two parameters, why is this object not in the variable manager? Its not something specific to this feature, the same comment could be applied to the cellIconURLsProvider and the cellValueProvider.

It seems like a bad pattern being propagated again and again...

File: packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls [hunk 2]
```diff
@@ -106,6 +106,7 @@ interface Cell {
   columnId: ID!
   targetObjectId: ID!
   targetObjectKind: String!
+  tooltipValue: String!
```
Comment (sbegaudeau) [inline packages/tables/backend/sirius-components-collaborative-tables/src/main/resources/schema/table.graphqls:109]: When we had discussions on the support for tooltip in the past for other representations, it was concluded that tooltips are closer to a palette and should thus be requested on the fly instead of being computed again and again thousands of times per refresh for probably nothing. A sizable part of the code of this contribution could be removed by lazily requesting the tooltip on over in the frontend (no need to have them in the description, the components, the elements, the custom widget, etc).

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/table/CellDescriptionConverter.java [hunk 3]
```diff
@@ -93,12 +93,19 @@ private Optional<ICellDescription> convert(org.eclipse.sirius.components.view.ta
             return this.evaluateString(interpreter, child, viewCellDescription.getValueExpression());
         };
 
+        BiFunction<VariableManager, Object, String> cellTooltipValueProvider = (variableManager, columnTargetObject) -> {
+            var child = variableManager.createChild();
+            child.put("columnTargetObject", columnTargetObject);
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/table/CellDescriptionConverter.java:98]: So the second parameter could indeed be given in the variable manager.

File: packages/tables/frontend/sirius-components-tables/src/cells/Cell.tsx [hunk 4]
```diff
@@ -128,9 +129,11 @@ export const Cell = memo(
         }
       }
       return (
-        <div className={classes.wrapper} onClick={() => onClick(cell)}>
-          {component}
-        </div>
+        <Tooltip title={cell.tooltipValue}>
```
Comment (sbegaudeau) [inline packages/tables/frontend/sirius-components-tables/src/cells/Cell.tsx:132]: The tooltip seems a bit far from the real cell, it can almost seem to be on the next cell

**Review by sbegaudeau — APPROVED** [review]
I'll rebase, merge it and perform a release to let downstream project consume the latest improvements.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/table/customcells/CheckboxCellComponent.java [hunk 5]
```diff
@@ -40,7 +40,9 @@ public Element render() {
         String targetObjectKind = cellDescription.getTargetObjectKindProvider().apply(variableManager);
 
         Boolean value = cellDescription.getCellValueProvider().apply(variableManager, this.props.columnTargetObject());
-        CheckboxCellElementProps cellElementProps = new CheckboxCellElementProps(this.props.cellId(), this.props.checkboxCellDescription().getId(), targetObjectId, targetObjectKind, this.props.columnId(), value);
+        String tooltipValue = cellDescription.getCellTooltipValueProvider().apply(variableManager, this.props.columnTargetObject());
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/table/customcells/CheckboxCellComponent.java:43]: FWIW, it looks like this will imply evaluating possibly hundreds/thousands of expressions on *every render* of a table, even though in practice 99.9% of the cells' tooltips will never be displayed (and that's probably generous).
Given that tooltips are only displayed on the fronted after a small delay anyway, would it be possible to only compute them lazily/on-demand though a dedicated query/data fetcher?

Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/table/customcells/CheckboxCellComponent.java:43]: I have opened [an issue](https://github.com/eclipse-sirius/sirius-web/issues/4925) for that but merge this in the meantime
