### PR TITLE
[fix] Add a SuccessPayload to replace most basic payloads

### LINKED ISSUE #1614: Add a `SuccessPayload` to replace most basic payloads
A lot of our payloads are just containing a single field `id`. They could all be replaced with a `SuccessPayload` in a similar fashion as our `ErrorPayload`.

### PR DESCRIPTION
**Pull request by mcharfadi**
Bug: #1614
Signed-off-by: Michaël Charfadi <michael.charfadi@obeosoft.com>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts [hunk 1]
```diff
@@ -256,7 +256,7 @@ export const fadeDiagramElementMutation = gql`
   mutation fadeDiagramElement($input: FadeDiagramElementInput!) {
     fadeDiagramElement(input: $input) {
       __typename
-      ... on FadeDiagramElementSuccessPayload {
+      ... on SuccessPayload {
```
Comment (gcoutable) [inline packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts:259]: What about `EditLabelSuccessPayload` and some other success payloads in this file? 
We do not use this payload specifically, not like `InvokeSingleClickOnDiagramElementToolSuccessPayload`.

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx [hunk 2]
```diff
@@ -66,7 +66,7 @@ import {
 import { Group } from './Group';
 import { Button } from './icons/Button';
 import { isKind } from './WidgetOperations';
-const isErrorPayload = (payload: GQLWidgetOperationPayload): payload is GQLErrorPayload =>
+const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
```
Comment (AxelRICHARD) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx]: Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx [hunk 3]
```diff
@@ -133,7 +133,7 @@ const GroupTooltip = withStyles((theme: Theme) => ({
   },
 }))(Tooltip);
 
-const isErrorPayload = (payload: GQLWidgetOperationPayload): payload is GQLErrorPayload =>
+const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
```
Comment (AxelRICHARD) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/Group.tsx]: Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx [hunk 4]
```diff
@@ -104,7 +104,7 @@ const useStyles = makeStyles<Theme, ButtonStyleProps>((theme) => ({
   },
 }));
 
-const isErrorPayload = (payload: GQLWidgetOperationPayload): payload is GQLErrorPayload =>
+const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
```
Comment (AxelRICHARD) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActionWidget.tsx]: Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActions.tsx [hunk 5]
```diff
@@ -66,7 +66,7 @@ const useToolbarActionsStyles = makeStyles<Theme>((theme: Theme) => ({
   },
 }));
 
-const isErrorPayload = (payload: GQLWidgetOperationPayload): payload is GQLErrorPayload =>
+const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
```
Comment (AxelRICHARD) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/ToolbarActions.tsx]: Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx [hunk 6]
```diff
@@ -113,7 +113,7 @@ const WidgetTooltip = withStyles((theme: Theme) => ({
   },
 }))(Tooltip);
 
-const isErrorPayload = (payload: GQLWidgetOperationPayload): payload is GQLErrorPayload =>
+const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
```
Comment (AxelRICHARD) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/WidgetEntry.tsx]: Are you sure about this? It seems strange that a GQLSuccessPayload could be a GQLErrorPayload.

File: packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts (hunk 1 above)
Comment (gcoutable) [reply packages/diagrams/frontend/sirius-components-diagrams/src/representation/operations.ts:259]: You may need to look for all the `**SuccessPayload` in this file and look if they cannot be transformed into `SuccessPayload` (or maybe simply removed from there).

**Review by gcoutable — DISMISSED** [review]

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.types.ts [hunk 7]
```diff
@@ -223,5 +244,32 @@ export interface GQLMoveGroupMutationVariables {
...
 
 export interface GQLMoveGroupMutationData {
-  moveGroup: GQLWidgetOperationPayload;
+  moveGroup: GQLMoveGroupPayload;
 }
+
+export interface GQLMoveGroupPayload {
+  __typename: string;
+}
+export interface GQLErrorPayload
```
Comment (AxelRICHARD) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.types.ts:254]: Are you sure about this? Shouldn't it be the opposite?

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.tsx [hunk 8]
```diff
@@ -29,13 +29,13 @@ import {
...
   GQLMoveWidgetMutationVariables,
-  GQLWidgetOperationPayload,
+  GQLSuccessPayload,
 } from './FormDescriptionEditorEventFragment.types';
 import { WidgetEntry } from './WidgetEntry';
 import { FlexboxContainerWidgetProps } from './WidgetEntry.types';
 import { getAllToolbarActions, isKind } from './WidgetOperations';
 
-const isErrorPayload = (payload: GQLWidgetOperationPayload): payload is GQLErrorPayload =>
+const isErrorPayload = (payload: GQLSuccessPayload): payload is GQLErrorPayload =>
```
Comment (sbegaudeau) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FlexboxContainerWidget.tsx]: This cannot be true, ever

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.types.ts (hunk 7 above)
Comment (sbegaudeau) [reply packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorEventFragment.types.ts:254]: How so?

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx (hunk 2 above)
Comment (sbegaudeau) [reply packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/FormDescriptionEditorRepresentation.tsx]: It can never be true

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

**Comment by sbegaudeau** [comment]
There is still an outdated reference to `GQLAddWidgetSuccessPayload` among the 926 references to a `XxxSuccessPayload` in the code. I'll handle it and update the pull request accordingly.

Please also ensure that your commit messages are properly formatted with the full URL of the bug after `Bug:`. I'll raise an issue to perform this kind of check automatically.

**Comment by sbegaudeau** [comment]
I still have some manual tests to perform before merging this PR

**Review by sbegaudeau — APPROVED** [review]
