### PR TITLE
[3317] Prevent rendering infinite loop during multi selection

### LINKED ISSUE #3317: A crash occurs after selection changes are made too quickly
When changing selection with `shift`+ select, there is an infinite renderer loop that crashes application
selection-crash

### PR DESCRIPTION
**Pull request by frouene**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/3317

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx [hunk 1]
```diff
@@ -154,6 +154,16 @@ export const DiagramRenderer = ({ diagramRefreshedEventPayload }: DiagramRendere
...
 
+  useEffect(() => {
+    setEdges((edges: Edge<EdgeData>[]) =>
+      edges.map((edge) => {
+        edge.updatable =
+          selection.entries.map((element) => element.id).includes(edge.data?.targetObjectId ?? '') && !readOnly;
+        return edge;
+      })
+    );
+  }, [selection]);
```
Comment (mcharfadi) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx]: You don't want an object in the dependency array here or it could lead to unnecessary rerenders when the value is the same. For example, clicking on the same item in the explorer will trigger a rerender, other scenario might trigger a rerender when we don't need one. Please note that it could also be avoided by memoising the selection in the `SelectionContext`.
Also note that we trigger a setEdges even if the selection change was not about edges, when selecting a lot of elements this might have some impacts. Maybe using `useOnSelectionChange` hook would allow for a more precise behavior.

**Review by mcharfadi — CHANGES_REQUESTED** [review]

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx (hunk 1 above)
Comment (frouene) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx]: I changed this part to only active edge if it's selected and not if an element with same targeObjectId is selected

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx [hunk 2]
```diff
@@ -154,6 +154,12 @@ export const DiagramRenderer = ({ diagramRefreshedEventPayload }: DiagramRendere
     }
   }, [diagramRefreshedEventPayload, diagramDescription]);
 
+  useEffect(() => {
+    if (edges.length > 0) {
+      setEdges(edges.map((edge) => ({ ...edge, updatable: !!edge.selected })));
+    }
+  }, [JSON.stringify(edges)]);
```
Comment (mcharfadi) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx]: `JSON.stringify` does not make it clear why we rerender and will make us rerender with any change in any edges.
I think something like [selection.entries.map((selection) => selection.id).join()] or anything more "precise" will be more efficient.
Also `edges.length> 1` is doing nothing since if edges changes that would mean you have more than one edge

**Review by mcharfadi — CHANGES_REQUESTED** [review]

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx (hunk 2 above)
Comment (frouene) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx]: done

**Review by mcharfadi — APPROVED** [review]
