### PR TITLE
[4944] Fix a bug when uploading models introduced in 2025.4.2

### LINKED ISSUE #4944: Regression on reference handling when uploading models with EMF JSON 2.5.0
When we upload a document model, one of the steps we do once the model has been load in memory is to serialize it in memory using a special IDManager and then re-load the result, to ensure all model elements get "fresh" ids, and avoid duplicates if the same file/document is uploaded multiple times.

The IDManager used for that is `EObjectRandomIDManager`, which returns a *new* random UUID on *every* call to `getOrCreateId(EObject)`.

Starting from EMF JSON 2.5.0, we invoke `getOrCreateId(EObject)` not only once per model element to serialize it, but also when serializing *references* to a model element. So if we have a model element A which references r1, r2 pointing to it, we will call `getOrCreateId(EObject)` once to serialize A, once to serialize r1, once for r2. And with `EObjectRandomIDManager`, we'll get a different, inconsistent value for the 3 invocations.

### PR DESCRIPTION
**Pull request by pcdavid**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/4944
Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java [hunk 1]
```diff
@@ -46,6 +53,8 @@
 @Service
 public class DocumentSanitizedJsonContentProvider implements IDocumentSanitizedJsonContentProvider {
 
+    private final FadeButtonDescriptionProvider fadeButtonDescriptionProvider;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java]: Huh?

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
The content assist of your IDE may have made an error :)

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java (hunk 1 above)
Comment (pcdavid) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java]: Fixed. Looks like an automatic imported added at some point by Eclipse that I did not see.

Comment (pcdavid) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java]: Or some issue with git applying the patch I exported from another clone.
I don't even know about this class so it was not voluntary.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java [hunk 2]
```diff
@@ -120,6 +128,23 @@ public Optional<String> getContent(ResourceSet resourceSet, String name, InputSt
         return optionalContent;
     }
 
+    /**
+     * Give fresh, unique IDs to all the elements in the resource.
+     */
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java:133]: Improvements have been made to the performance of the upload among other things, can't we do better than an additional eAllContents? Why is that necessary to iterate once again on everything?

Comment (pcdavid) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/services/DocumentSanitizedJsonContentProvider.java:133]: This is more of an "emergency fix", and I did not want to make more signigicant changes for the moment.

My guess is that somehting like this could actually completely replace DocumentSanitizedJsonContentProvider (whose whole point is to ensure the imported elements has fresh, non-conflicting ids), but that would invole more stuctural changes.

**Review by sbegaudeau — APPROVED** [review]
I'll wait for the build and merge it
