### PR TITLE
[3606] Improve error handling for ExecuteEditingContextFunction

### LINKED ISSUE #3606: Improve error handling for ExecuteEditingContextFunction
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
The `ExecuteEditingContextFunctionRunner` should return an `IPayload`, allowing to return an `ErrorPayload` if something went wrong during the handling of the input.
The `ExecuteEditingContextFunctionEventHandler` should catch exceptions thrown by the called function and return an `ErrorPayload` if such exception is caught.

### PR DESCRIPTION
**Pull request by gdaniel**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/3606

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java [hunk 1]
```diff
@@ -35,10 +35,18 @@ public boolean canHandle(IEditingContext editingContext, IInput input) {
...
-            payloadSink.tryEmitValue(new ExecuteEditingContextFunctionSuccessPayload(input.id(), result));
+            Object result = null;
+            try {
+                result = executeEditingContextFunctionInput.function().apply(editingContext);
+            } catch (Throwable e) {
+                payloadSink.tryEmitValue(new ErrorPayload(input.id(), e.getMessage()));
+            }
+            if (result != null) {
+                payloadSink.tryEmitValue(new ExecuteEditingContextFunctionSuccessPayload(input.id(), result));
+            }
```
Comment (sbegaudeau) [inline packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java]: Wouldn't that send two ErrorPayload in case of an exception?

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java (hunk 1 above)
Comment (gdaniel) [reply packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java]: Interestingly this wasn't an issue although the existing code was already producing multiple payloads if the function call succeeded (the success payload and the error payload after the `if`). I fixed it to use the pattern we have in other handlers with a single `tryEmitValue` call.

File: packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java [hunk 2]
```diff
@@ -29,17 +30,35 @@
...
+        String message = this.messageService.invalidInput(input.getClass().getSimpleName(), ExecuteEditingContextFunctionInput.class.getSimpleName());
+        IPayload payload = new ErrorPayload(input.id(), message);
+
         if (input instanceof ExecuteEditingContextFunctionInput executeEditingContextFunctionInput) {
-            var result = executeEditingContextFunctionInput.function().apply(editingContext);
-            payloadSink.tryEmitValue(new ExecuteEditingContextFunctionSuccessPayload(input.id(), result));
+            Object result = null;
+            try {
+                result = executeEditingContextFunctionInput.function().apply(editingContext);
+            } catch (Throwable e) {
```
Comment (sbegaudeau) [inline packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java]: catching exception should be more than enough, I don't see the need to catch OutOfMemoryErrors or things like that :)

File: packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java [hunk 3]
```diff
@@ -29,17 +30,35 @@
...
+                payload = new ErrorPayload(input.id(), e.getMessage());
+            }
+            if (result != null) {
+                payload = new ExecuteEditingContextFunctionSuccessPayload(input.id(), result);
+            }
```
Comment (sbegaudeau) [inline packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java]: `null` can be a perfectly valid result, we should probably ask to return a payload instead to not decide instead of the tester

File: packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java [hunk 4]
```diff
@@ -29,17 +30,35 @@
...
         }
-        payloadSink.tryEmitValue(new ErrorPayload(input.id(), "Invalid payload"));
+        payloadSink.tryEmitValue(payload);
```
Comment (sbegaudeau) [inline packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java:65]: I'll also add the ability to customize the change description fired because otherwise, the change performed by the function cannot trigger a refresh which is painful to trigger after that

File: packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java (hunk 3 above)
Comment (sbegaudeau) [reply packages/tests/backend/sirius-components-graphql-tests/src/main/java/org/eclipse/sirius/components/graphql/tests/ExecuteEditingContextFunctionEventHandler.java]: I'll also give access to the input in order to compute the payload accordingly

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

**Review by sbegaudeau — APPROVED** [review]

**Comment by sbegaudeau** [comment]
Now we will have way more options, we can decide the payload returned and potential side effects with the change description
