### PR TITLE
[5070] Prevent nodes from dropping onto the diagram background instea…

### LINKED ISSUE #5070: When layouting Node in a parent with a free form layout, the node is often incorrectly removed from its parent node
* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have checked that this bug appears on Chrome**
* [X] **I have specified the version** :
- latest
### Screenshots

...

### Steps to reproduce

When layouting nodes (moving or resizing) inside a Freeform Compartement it often happens that the nodes is moved outside the compartment and a semantic change is applied.

See video

https://github.com/user-attachments/assets/bf945faf-4cfc-4a1a-bc4e-28adc6820863

Sometimes we get strange error message:

Image

Image

Here is a the backend log:

```
app-1       | 2025-06-13T08:28:11.952Z  WARN 1 --- [nio-8080-exec-2] o.e.s.c.g.controllers.GraphQLController  : {
app-1       |   "errors" : [ {
app-1       |     "message" : "The field at path '/viewer/editingContext/representation/description/palette' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'Palette' within parent type 'DiagramDescription'",
app-1       |     "path" : [ "viewer", "editingContext", "representation", "description", "palette" ],
app-1       |     "extensions" : {
app-1       |       "classification" : "NullValueInNonNullableField"
app-1       |     }
app-1       |   } ],
app-1       |   "data" : {
app-1       |     "viewer" : {
app-1       |       "editingContext" : {
app-1       |         "representation" : null,
app-1       |         "__typename" : "EditingContext"
app-1       |       },
app-1       |       "__typename" : "Viewer"
app-1       |     }
app-1       |   }
```

...

### Expected behavior

The node should not move outside of this container.

### Actual behavior

The move is move outside of the container and a semantic change happen.

### PR DESCRIPTION
**Pull request by frouene**
…d of its target node

Bug: https://github.com/eclipse-sirius/sirius-web/issues/5070

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Review by mcharfadi — CHANGES_REQUESTED** [review]
I see improvements on the specific case that is tested here but I found a regression in flow
I guess this case with flow should also be tested
https://github.com/user-attachments/assets/6bfdc924-04f4-475a-9dcf-b723e1c47022

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts [hunk 1]
```diff
@@ -190,16 +190,15 @@ export const useDropNode = (): UseDropNodeValue => {
...
-            return {
-              ...n,
-              data: {
-                ...n.data,
-                isDropNodeCandidate: true,
-              },
-            };
-          }
-          return n;
+          return {
```
Comment (mcharfadi) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/dropNode/useDropNode.ts]: If I understood the issue correctly, it seems that when dragging too fast then `isDropNodeTarget `is not already set so the diagram is taken for target instead. 
Maybe we could just add something like that in `onNodeDragStart`

```
          if (computedNode.parentId === n.id) {
            return {
              ...n,
              data: {
                ...n.data,
                isDropNodeTarget: true,
              },
            };
          }
```

Also note that if you're removing the condition here, then all the nodes of the diagram will be rerendered when starting a drag.

**Review by mcharfadi — APPROVED** [review]

**Review by mcharfadi — COMMENTED** [review]
Seems like the issue on flow was not related to the PR.
The PR fixes the issue and can be merged
