### PR TITLE
[2360, 2456] Fix two issues on widget ref creation modal 

### LINKED ISSUE #2360: It is not possible to create a new object on some containment reference with the reference widget
For a containment reference, if the containing class of the feature reference is abstract, it's not possible to create a new object with the reference widget, cause the options in the creation modal is empty.

For example, with a reference _outgoingFlows_ in the _Flow_ model.

### LINKED ISSUE #2456: The create element on a widget ref for a mono valued and containment reference isn't working if there is already a value.
* [x] **I have checked that this bug has not yet been reported by someone else**
* [ ] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest

### Steps to reproduce

An example model with a mono valued and containment reference: 

[Studio.zip](https://github.com/eclipse-sirius/sirius-web/files/12846296/Studio.zip)

With a widget reference on this reference, if there is already a value setted, then the create new element action is not working.

### Actual behavior

Nothing append and there is a snackbar with a generic error.

### PR DESCRIPTION
**Pull request by frouene**
# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/PropertiesWidgetCreationService.java [hunk 1]
```diff
@@ -343,6 +343,13 @@ private IStatus handleAddReferenceValues(VariableManager variableManager, Object
 
     private Object handleCreateElement(VariableManager variableManager, Object feature) {
         Optional<Object> result = Optional.empty();
+        if (this.isContainment(variableManager, feature) && !this.isMany(variableManager, feature)) {
+            // If the reference is containment and mono valued, we must first unset value before create a new one
+            EObject referenceOwner = variableManager.get(VariableManager.SELF, EObject.class).orElse(null);
+            if (referenceOwner != null && feature instanceof EReference reference) {
+                referenceOwner.eUnset(reference);
+            }
+        }
```
Comment (pcdavid) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/PropertiesWidgetCreationService.java]: I'd put this inside the `if (optionalIsChild.isPresent() && optionalEditingContext.isPresent())` block below, to avoid modifying the reference in cases where we discover a few lines later that we can not actually create the new element.

File: packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java [hunk 2]
```diff
@@ -353,6 +353,14 @@ private IStatus handleAddReference(VariableManager variableManager, ReferenceWid
...
     private Object handleCreateElement(VariableManager variableManager, ReferenceWidgetDescription referenceDescription) {
         Optional<Object> result = Optional.empty();
+        if (this.isContainment(variableManager, referenceDescription) && !this.isMany(variableManager, referenceDescription)) {
+            // If the reference is mono valued and containment, we must first unset value before create a new one
+            EObject owner = this.getReferenceOwner(variableManager, referenceDescription.getReferenceOwnerExpression());
+            String referenceName = this.getStringValueProvider(referenceDescription.getReferenceNameExpression()).apply(variableManager);
+            if (owner != null && owner.eClass().getEStructuralFeature(referenceName) instanceof EReference reference) {
+                owner.eUnset(reference);
+            }
+        }
```
Comment (pcdavid) [inline packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java]: I'd put this inside the if (optionalIsChild.isPresent() && optionalEditingContext.isPresent()) block below, to avoid modifying the reference in cases where we discover a few lines later that we can not actually create the new element.

**Review by pcdavid — CHANGES_REQUESTED** [review]

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/PropertiesWidgetCreationService.java (hunk 1 above)
Comment (frouene) [reply packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/compatibility/PropertiesWidgetCreationService.java]: You're right, I've moved it

File: packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java (hunk 2 above)
Comment (frouene) [reply packages/forms/backend/sirius-components-collaborative-widget-reference/src/main/java/org/eclipse/sirius/components/collaborative/widget/reference/ReferenceWidgetDescriptionConverterSwitch.java]: You're right, I've moved it

**Review by pcdavid — APPROVED** [review]
