### PR TITLE
[1521] Canonical creation tools from contextual toolbar have no icons

### LINKED ISSUE #1521: Canonical creation tools from contextual toolbar have no icons
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2022.11.13
* [x] **I have specified my environment** : 
- my computer: macOS

### Screenshots

ToolNoIcon

### Steps to reproduce

1. Your SiriusWeb instance should not have the Domain package, only View package
2. Create a View model 
3. Create a Diagram Description that applies on an existing class from a metamodel (not from a Domain)
4. Create a valid Node that applies on an existing class from the same metamodel
5. Create a Diagram from the Diagram Description
6. Click on the diagram background: a creation tool is provided by default, based on the Diagram Description and the View.

### Expected behavior

The canonical creation tool provided by default should have an icon, ideally the icon associated to the EClass/DomainClass.

### Actual behavior

The canonical creation tool provided by default doesn't have any icon.

### Help resources

The problem comes from `ViewDiagramDescriptionConverter.java`. `String NODE_CREATION_TOOL_ICON = "/img/Entity.svg";` & `EDGE_CREATION_TOOL_ICON = "/img/Relation.svg";` refer to SVG coming from Domain package.

### Solution proposed

1. `String NODE_CREATION_TOOL_ICON = "/img/Entity.svg";` & `EDGE_CREATION_TOOL_ICON = "/img/Relation.svg";` should refer to SVG from View package.

2. Canonical creation tools should try to get icons associated to the EClass/DomainClass and fallback to a default icon on failure.

### PR DESCRIPTION
**Pull request by AxelRICHARD**
# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [x] Does the title of the commit contributing the ADR start with `[doc]`?
- [x] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [x] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/configuration/ViewEMFConfiguration.java [hunk 1]
```diff
@@ -39,4 +44,9 @@ public ViewEMFConfiguration(Registry eValidatorRegistry) {
     public void registerViewValidator() {
         this.eValidatorRegistry.put(ViewPackage.eINSTANCE, new DiagramDescriptionValidator());
     }
+
+    @Bean
+    public IViewToolImageProviderFactory viewToolImageProviderFactory(IObjectService objectService, EPackage.Registry ePackageRegistry) {
+        return viewDiagramElementDescription -> new ViewToolImageProvider(objectService, ePackageRegistry, viewDiagramElementDescription);
+    }
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/configuration/ViewEMFConfiguration.java]: This is useless

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IViewToolImageProviderFactory.java [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+import java.util.function.Supplier;
+
+import org.eclipse.sirius.components.view.DiagramElementDescription;
+
+/**
+ * Used to provide a function which will give us the image path for a View tool.
+ *
+ * @author arichard
+ */
+public interface IViewToolImageProviderFactory {
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/IViewToolImageProviderFactory.java]: This is useless

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java [hunk 3]
```diff
@@ -308,17 +309,37 @@ private boolean matches(AQLInterpreter interpreter, String condition, VariableMa
...
+                .build();
+        return List.of(nodeCreationToolSection, edgeCreationToolSection);
+        // @formatter:on
+    }
+
+    private List<ITool> getNodeTools(ViewDiagramDescriptionConverterContext converterContext, Map<org.eclipse.sirius.components.view.NodeDescription, NodeDescription> capturedConvertedNodes) {
         List<ITool> nodeCreationTools = new ArrayList<>();
         for (var nodeDescription : converterContext.getConvertedNodes().keySet()) {
             List<NodeDescription> allTargetDescriptions = this.getAllTargetDescriptions(nodeDescription, converterContext);
+            String imageURL = this.viewToolImageProviderFactory.getToolImageProvider(nodeDescription).get();
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java]: The tool image provider should be a stateless service and you should call `get(nodeDescription)` instead

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java [hunk 4]
```diff
@@ -348,16 +369,21 @@ private List<ToolSection> createToolSections(ViewDiagramDescriptionConverterCont
                 nodeCreationTools.add(tool);
             }
         }
+        return nodeCreationTools;
+    }
 
+    private List<ITool> getEdgeTools(ViewDiagramDescriptionConverterContext converterContext, Map<org.eclipse.sirius.components.view.NodeDescription, NodeDescription> capturedConvertedNodes) {
         List<ITool> edgeTools = new ArrayList<>();
         for (var edgeDescription : converterContext.getConvertedEdges().keySet()) {
+            String imageURL = this.viewToolImageProviderFactory.getToolImageProvider(edgeDescription).get();
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewDiagramDescriptionConverter.java]: Same comment

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewToolImageProvider.java [hunk 5]
```diff
@@ -0,0 +1,102 @@
...
+import org.eclipse.sirius.components.view.EdgeDescription;
+import org.eclipse.sirius.ecore.extender.business.api.accessor.EcoreMetamodelDescriptor;
+import org.eclipse.sirius.ecore.extender.business.internal.accessor.ecore.EcoreIntrinsicExtender;
+
+/**
+ * Class used to compute the image of a View tool.
+ *
+ * @author arichard
+ */
+public class ViewToolImageProvider implements Supplier<String> {
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewToolImageProvider.java]: This should be a service and it should come with its dedicated interface

File: packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java [hunk 6]
```diff
@@ -138,7 +141,13 @@ private Diagram render(DiagramDescription diagramDescription, Object target) {
         res.getContents().add(view);
         new ResourceSetImpl().getResources().add(res);
 
-        ViewDiagramDescriptionConverter diagramDescriptionConverter = new ViewDiagramDescriptionConverter(new IObjectService.NoOp(), new IEditService.NoOp(), List.of());
+        var viewToolImageProviderFactory = new IViewToolImageProviderFactory() {
+            @Override
+            public Supplier<String> getToolImageProvider(DiagramElementDescription viewDiagramElementDescription) {
+                return () -> ""; //$NON-NLS-1$
+            }
+        };
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/test/java/org/eclipse/sirius/components/view/emf/view/DynamicDiagramsTests.java]: Can be removed

**Comment by sbegaudeau** [comment]
While using some existing code as source of inspiration can be a good idea, sometimes the existing code may be full of issues as it is the case on that topic. Things can be just as powerful with less complexity. I'll fix that on this new contribution and on the original one.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

**Review by sbegaudeau — APPROVED** [review]
