### PR TITLE
[2152] Simplify the filtering of tree items by removing the regular expression used

### LINKED ISSUE #2152: Some characters typed in the filter bar raise exception
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2023.6.4
* [x] **I have specified my environment** : 
- All

### Steps to reproduce

1. Activate the filter bar in the Explorer view
2. Type one of the RegExp special characters ^, /, $, (, *, [....

### Expected behavior

The filter bar accepts all characters

### Actual behavior

The filter bar raise an exception

### PR DESCRIPTION
**Pull request by AxelRICHARD**
Bug: https://github.com/eclipse-sirius/sirius-components/issues/2152

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Review by sbegaudeau — COMMENTED** [review]
I'll update this PR to restore support for case insensitivity and I'll change the commit message to indicate what this commit does (and match our commit conventions)

File: packages/trees/frontend/sirius-components-trees/src/treeitems/filterTreeItem.ts [hunk 1]
```diff
@@ -12,19 +12,48 @@
...
+  const splitLabelWithTextToHighlight: string[] = splitText(treeItem.label, textToHighlight);
   if (splitLabelWithTextToHighlight.length > 1) {
     filter = false;
   } else if (!treeItem.hasChildren && splitLabelWithTextToHighlight.length === 1) {
     filter = true;
   } else if (
     treeItem.hasChildren &&
     treeItem.expanded &&
-    treeItem.children.map((child) => child.label.split(highlightRegExp).length).every((v) => v === 1)
+    treeItem.children.map((child) => child.label.split(textToHighlight).length).every((v) => v === 1)
```
Comment (AxelRICHARD) [inline packages/trees/frontend/sirius-components-trees/src/treeitems/filterTreeItem.ts]: May be we should also use `splitText` here, because `split` will be sensitive-case. What do you think about?

Comment (sbegaudeau) [reply packages/trees/frontend/sirius-components-trees/src/treeitems/filterTreeItem.ts]: The issue in reusing spliText here is that it would also reinsert the separator (the part with flatMap), we should probably just use toLowerCase. Could you update the PR for that?

Comment (AxelRICHARD) [reply packages/trees/frontend/sirius-components-trees/src/treeitems/filterTreeItem.ts]: Ok I'll do that

File: packages/trees/frontend/sirius-components-trees/src/treeitems/__tests__/filterTreeItem.test.ts [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+ * SPDX-License-Identifier: EPL-2.0
+ *
+ * Contributors:
+ *     Obeo - initial API and implementation
+ *******************************************************************************/
+
+import { expect, test } from 'vitest';
+import { splitText } from '../filterTreeItem';
+
+test('should split text in a case insensitive manner', () => {
```
Comment (pcdavid) [inline packages/trees/frontend/sirius-components-trees/src/treeitems/__tests__/filterTreeItem.test.ts:17]: Strange that this does not test for splitting on the special characters which triggers this whole ticket.

File: packages/trees/frontend/sirius-components-trees/src/treeitems/filterTreeItem.ts [hunk 3]
```diff
@@ -12,19 +12,54 @@
  *******************************************************************************/
 import { GQLTreeItem } from '../views/ExplorerView.types';
 
-export const isFilterCandidate = (treeItem: GQLTreeItem, highlightRegExp: RegExp): boolean => {
+export const splitText = (label: string, userInput: string | null): string[] => {
+  if (!userInput) {
+    return [label];
+  }
+
+  const newLC = label.toLowerCase().split(userInput.toLocaleLowerCase());
```
Comment (pcdavid) [inline packages/trees/frontend/sirius-components-trees/src/treeitems/filterTreeItem.ts]: Never used.

**Review by pcdavid — CHANGES_REQUESTED** [review]

**Review by pcdavid — APPROVED** [review]
