### PR TITLE
[4077] Remove metadata from Charts widgets

### LINKED ISSUE #4077: Remove metadata from Chart widgets
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2024.9.5
* [x] **I have specified my environment** : 
- All

### Stack

```
java.util.concurrent.CompletionException: The field at path '/formEvent' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'FormRefreshedEventPayload' within parent type 'Subscription'
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[na:na]
    at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674) 
....
```

and

```
Caused by: graphql.execution.NonNullableFieldWasNullException: The field at path '/formEvent/form/pages[0]/groups[0]/widgets[0]/chart/metadata' was declared as a non null type, but the code involved in retrieving data has wrongly returned a null value.  The graphql specification requires that the parent field be set to null, or if that is non nullable that it bubble up null to its parent and so on. The non-nullable type is 'RepresentationMetadata' within parent type 'PieChart'
    at graphql.execution.NonNullableFieldValidator.validate(NonNullableFieldValidator.java:49) ~[graphql-java-22.1.jar:na]
    at graphql.execution.ExecutionStrategy.completeValueForNull(ExecutionStrategy.java:748) ~[graphql-java-22.1.jar:na]
    ....
```

### Steps to reproduce

Just create a PieChart or a BarChart with the View DSL.

### Expected behavior

PieChart and BarChart can be displayed in forms

### Actual behavior

PieChart and BarChart cannot be displayed in forms

### PR DESCRIPTION
**Pull request by AxelRICHARD**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/4077

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/BarChart.java [hunk 1]
```diff
@@ -169,6 +176,11 @@ public Builder height(int height) {
             return this;
         }
 
+        public Builder yAxisLabel(String yAxisLabel) {
+            this.yAxisLabel = yAxisLabel;
```
Comment (pcdavid) [inline packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/BarChart.java]: Is it voluntary not to check for null-ness?

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java [hunk 2]
```diff
@@ -171,6 +184,7 @@ public BarChartElementProps build() {
             barChartElementProps.style = this.style; // Optional on purpose
             barChartElementProps.width = this.width;
             barChartElementProps.height = this.height;
+            barChartElementProps.yAxisLabel = this.yAxisLabel;
```
Comment (pcdavid) [inline packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java]: Is it optional on purpose? The GraphQL definition (`String!`) seems to imply no.

File: packages/charts/frontend/sirius-components-charts/src/pie/PieChart.tsx
Comment (pcdavid) [inline packages/charts/frontend/sirius-components-charts/src/pie/PieChart.tsx:1]: Copyright updated but no actual change in the file; not sure this is normal/expected.

File: packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
Comment (pcdavid) [inline packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts:1]: Can the `interface GQLChartMetadata` be removed?

File: packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts [hunk 3]
```diff
@@ -18,17 +18,14 @@ export interface BarChartProps {
 }
 
 export interface BarChartRepresentation {
-  metadata: RepresentationMetadata;
+  label: string;
```
Comment (gcoutable) [inline packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts]: I don't see were this label is used

File: packages/charts/frontend/sirius-components-charts/src/pie/PieChart.types.ts [hunk 4]
```diff
@@ -20,6 +20,7 @@ export interface PieChartProps {
 }
 
 export interface PieChartRepresentation {
+  label: string;
```
Comment (gcoutable) [inline packages/charts/frontend/sirius-components-charts/src/pie/PieChart.types.ts]: I don't see were this label is used

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java [hunk 5]
```diff
@@ -160,6 +168,11 @@ public Builder height(int height) {
             return this;
         }
 
+        public Builder yAxisLabel(String yAxisLabel) {
+            this.yAxisLabel = yAxisLabel;
```
Comment (gcoutable) [inline packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java]: Objects.requireNonNull

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java (hunk 2 above)
Comment (gcoutable) [inline packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java]: Objects.requireNonNull

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/BarChartWidget.tsx [hunk 6]
```diff
@@ -72,6 +69,8 @@ export const BarChartWidget = ({ widget }: BarChartWidgetProps) => {
     style: barChartWidget.style,
     width: barChartWidget.width,
     height: barChartWidget.height,
+    yAxisLabel: 'Frequency',
+    label: widget.label,
```
Comment (gcoutable) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/BarChartWidget.tsx]: `label` is not needed

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PieChartWidget.tsx [hunk 7]
```diff
@@ -56,6 +56,7 @@ export const PieChartWidget = ({ widget }: PieChartWidgetProps) => {
       { key: '≥85', value: 5938752 },
     ],
     style: pieChartWidget.style,
+    label: widget.label,
```
Comment (gcoutable) [inline packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PieChartWidget.tsx]: `label` is not needed

File: packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx [hunk 8]
```diff
@@ -37,11 +37,30 @@ export const ChartWidgetPropertySection: PropertySectionComponent<GQLChartWidget
   if (isBarChart(chart)) {
     chartComponent = (
       <div className={classes.chart}>
-        <BarChart chart={chart} />
+        <BarChart
+          chart={{
+            label: widget.label,
```
Comment (gcoutable) [inline packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx]: `label` is not needed

File: packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx [hunk 9]
```diff
@@ -37,11 +37,30 @@ export const ChartWidgetPropertySection: PropertySectionComponent<GQLChartWidget
...
       </div>
     );
   } else if (isPieChart(chart)) {
-    chartComponent = <PieChart width={300} height={300} chart={chart} />;
+    chartComponent = (
+      <PieChart
+        width={300}
+        height={300}
+        chart={{
+          label: widget.label,
```
Comment (gcoutable) [inline packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx]: `label` is not needed

**Review by pcdavid — DISMISSED** [review]
Minor stuff

**Review by gcoutable — CHANGES_REQUESTED** [review]

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/BarChart.java (hunk 1 above)
Comment (AxelRICHARD) [reply packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/BarChart.java]: Yes, imho the Y Axis label should not be mandatory.

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java (hunk 5 above)
Comment (AxelRICHARD) [reply packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java]: imho the Y Axis label should not be mandatory.

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java (hunk 2 above)
Comment (AxelRICHARD) [reply packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java]: Yes, imho the Y Axis label should not be mandatory. I will update the graphql definition, it is a mistake.

Comment (AxelRICHARD) [reply packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java]: Yes, imho the Y Axis label should not be mandatory.

File: packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts (hunk 3 above)
Comment (AxelRICHARD) [reply packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts]: you're right, it is not used, I'll remove it

File: packages/charts/frontend/sirius-components-charts/src/pie/PieChart.tsx
Comment (AxelRICHARD) [reply packages/charts/frontend/sirius-components-charts/src/pie/PieChart.tsx:1]: Done

File: packages/charts/frontend/sirius-components-charts/src/pie/PieChart.types.ts (hunk 4 above)
Comment (AxelRICHARD) [reply packages/charts/frontend/sirius-components-charts/src/pie/PieChart.types.ts]: you're right, it is not used, I'll remove it

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/BarChartWidget.tsx (hunk 6 above)
Comment (AxelRICHARD) [reply packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/BarChartWidget.tsx]: done

File: packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PieChartWidget.tsx (hunk 7 above)
Comment (AxelRICHARD) [reply packages/formdescriptioneditors/frontend/sirius-components-formdescriptioneditors/src/PieChartWidget.tsx]: done

File: packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts
Comment (AxelRICHARD) [reply packages/forms/frontend/sirius-components-forms/src/form/FormEventFragments.types.ts:1]: It seems not used, indeed. I'll remove it.

File: packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx (hunk 8 above)
Comment (AxelRICHARD) [reply packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx]: done

File: packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx (hunk 9 above)
Comment (AxelRICHARD) [reply packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx]: done

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/BarChart.java (hunk 1 above)
Comment (gcoutable) [reply packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/BarChart.java]: The y Axis label may not be mandatory, but the value provided to the y axis label using this method should not be null

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java (hunk 5 above)
Comment (gcoutable) [reply packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java]: The y Axis label may not be mandatory, but the value provided to the y axis label using this method should not be null

File: packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts [hunk 10]
```diff
@@ -18,17 +18,13 @@ export interface BarChartProps {
 }
 
 export interface BarChartRepresentation {
-  metadata: RepresentationMetadata;
+  yAxisLabel: string;
```
Comment (gcoutable) [inline packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts]: if the value is optional: the type should be `string | null`

File: packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java (hunk 5 above)
Comment (AxelRICHARD) [reply packages/charts/backend/sirius-components-charts/src/main/java/org/eclipse/sirius/components/charts/barchart/elements/BarChartElementProps.java]: I don't see why it should not be null, we have other cases in ou basecode following the same pattern

**Review by gcoutable — CHANGES_REQUESTED** [review]

File: packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts (hunk 10 above)
Comment (AxelRICHARD) [reply packages/charts/frontend/sirius-components-charts/src/bar/BarChart.types.ts]: done

File: packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx [hunk 11]
```diff
@@ -37,11 +37,28 @@ export const ChartWidgetPropertySection: PropertySectionComponent<GQLChartWidget
...
     chartComponent = (
       <div className={classes.chart}>
-        <BarChart chart={chart} />
+        <BarChart
+          chart={{
+            entries: chart.entries,
+            height: chart.height,
+            width: chart.width,
+            yAxisLabel: chart.yAxisLabel,
+            style: chart.style,
```
Comment (gcoutable) [inline packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx]: Since you removed the label, you can revert that change too

File: packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx [hunk 12]
```diff
@@ -37,11 +37,28 @@ export const ChartWidgetPropertySection: PropertySectionComponent<GQLChartWidget
...
     );
   } else if (isPieChart(chart)) {
-    chartComponent = <PieChart width={300} height={300} chart={chart} />;
+    chartComponent = (
+      <PieChart
+        width={300}
+        height={300}
+        chart={{
+          entries: chart.entries,
+          style: chart.style,
```
Comment (gcoutable) [inline packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx]: Since you removed the label, you can revert that change too

File: packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx (hunk 11 above)
Comment (AxelRICHARD) [reply packages/forms/frontend/sirius-components-forms/src/propertysections/ChartWidgetPropertySection.tsx]: done

**Review by gcoutable — APPROVED** [review]
