### PR TITLE
[1339] Add concepts of layout strategy

### LINKED ISSUE #1339: Add support for children layout strategy
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

This feature will improve the layout engine. Soon, it will let us the possibility to contribute new children's layout strategy.
As a final user, I should not see any difference in my diagrams. I just may need to create them again.

### Potential side effects

Old diagrams may work, but the layout may be broken. Creating the diagram again should fix layout issues.

### PR DESCRIPTION
**Pull request by gcoutable**
# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+import org.eclipse.sirius.diagram.business.api.query.ContainerMappingQuery;
+import org.eclipse.sirius.diagram.description.AbstractNodeMapping;
+import org.eclipse.sirius.diagram.description.ContainerMapping;
+
+/**
+ * Used to compute the children layout strategy using the definition of an abstract node mapping.
+ *
+ * @author gcoutable
+ */
+public class AbstractNodeMappingChilrenLayoutStrategyProvider implements Function<VariableManager, ILayoutStrategy> {
```
Comment (pcdavid) [inline packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java]: Typo: `AbstractNodeMappingChil[d]renLayoutStrategyProvider`

File: packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+    public AbstractNodeMappingChilrenLayoutStrategyProvider(AbstractNodeMapping abstractNodeMapping) {
+        this.abstractNodeMapping = Objects.requireNonNull(abstractNodeMapping);
+    }
+
+    @Override
+    public ILayoutStrategy apply(VariableManager variableManager) {
+        return this.getChildrenLayoutStrategy(variableManager);
+    }
+
+    private ILayoutStrategy getChildrenLayoutStrategy(VariableManager variableManager) {
```
Comment (pcdavid) [inline packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java]: This doesn't use the `variableManager` at all.

File: packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java (hunk 1 above)
Comment (pcdavid) [reply packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java]: Atually, the whole class is not used at all, the equivalent code is directly in AbstractNodeMappingConverter.java. Except both versions do not behave exactly the same: this one will always return a non-null value and default to free form; the other only returns free-form if that was set explicitly in the VSM and null otherwise.

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java [hunk 3]
```diff
@@ -148,6 +150,8 @@ private Element doRender(VariableManager nodeVariableManager, String targetObjec
 
         INodeStyle style = nodeDescription.getStyleProvider().apply(nodeVariableManager);
 
+        ILayoutStrategy layoutStrategy = nodeDescription.getChildrenLayoutStrategyProvider().apply(nodeVariableManager);
+
         var borderNodes = this.getBorderNodes(optionalPreviousNode, nodeVariableManager, nodeId);
         var childNodes = this.getChildNodes(optionalPreviousNode, nodeVariableManager, nodeId);
```
Comment (pcdavid) [inline packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java:156]: could/should we void these computations if we know from the layout strategy that the border nodes and children will never be rendered/displayed?
this could have performance benefits, but we potentialy lose the custom layout/positions of the children if we switch back to a style where children make sense.

File: packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java (hunk 2 above)
Comment (pcdavid) [reply packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java]: Actually, the whole class does not seem to be used. The equivalent logic (except for the default case) is implemented directly in AbstractNodeMappingConverter. They differ in what strategy is return when nothing is specified explicitly (free form here, null there; not sure how null is interpreted during the rendering).

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/LayoutDirection.java [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+package org.eclipse.sirius.components.diagrams;
+
+/**
+ * The layout direction used by the {@link ListLayoutStrategy} to position the children of a node.
+ *
+ * @author gcoutable
+ */
+public enum LayoutDirection {
+    COLUMN
+}
```
Comment (pcdavid) [inline packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/LayoutDirection.java]: The ADR mentions that the `row` direction should be supported, and if we only support a single direction for the time being, we should not need this.

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java [hunk 5]
```diff
@@ -98,6 +100,14 @@ public INodeStyle getStyle() {
         return this.style;
     }
 
+    public ILayoutStrategy getChildrenLayoutStrategy() {
+        return this.childrenLayoutStrategy;
+    }
+
+    public static String getSelectedNode() {
+        return SELECTED_NODE;
+    }
```
Comment (pcdavid) [inline packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java]: Does this come from another patch? It seems unrelated and unused by the rest of the PR.

File: packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodePositionProviderTests.java [hunk 6]
```diff
@@ -61,7 +65,7 @@ public void testDiagramSeveralNewNodesAtOnce() {
         List<NodeLayoutData> nodes = new ArrayList<>();
         NodePositionProvider nodePositionProvider = new NodePositionProvider();
         DiagramLayoutData diagramLayoutData = this.createDiagramLayoutData();
-        NodeLayoutData nodeLayoutData = this.createNodeLayoutData(Position.UNDEFINED, DEFAULT_NODE_SIZE, diagramLayoutData, NodeType.NODE_RECTANGLE);
+        NodeLayoutData nodeLayoutData = this.createNodeLayoutData(Position.UNDEFINED, DEFAULT_NODE_SIZE, diagramLayoutData, NodeType.NODE_RECTANGLE, new FreeFormLayoutStrategy());
```
Comment (pcdavid) [inline packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodePositionProviderTests.java]: Given that `new FreeFormLayoutStrategy()` is added to the majority of calls, maybe there should be an overload of `createNodeLayoutData()` which makes this the default.

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/RectangularNodeStyle.java [hunk 7]
```diff
@@ -114,13 +122,19 @@ public Builder borderStyle(LineStyle borderStyle) {
             return this;
         }
 
+        public Builder withHeader(boolean withHeader) {
+            this.withHeader = Objects.requireNonNull(withHeader);
```
Comment (pcdavid) [inline packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/RectangularNodeStyle.java]: It a primitive `boolean`, this is not needed and will only cause an unnecessary boxing/unboxing.

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/RectangularNodeStyle.java [hunk 8]
```diff
@@ -34,6 +34,8 @@ public final class RectangularNodeStyle implements INodeStyle {
 
     private LineStyle borderStyle;
 
+    private boolean withHeader;
```
Comment (pcdavid) [inline packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/RectangularNodeStyle.java:37]: Should this new field be included in the `toString` result?

File: packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/SiriusWebLayoutConfigurator.java [hunk 9]
```diff
@@ -89,6 +104,14 @@ private SiriusWebLayoutConfigurator overrideWith(SiriusWebLayoutConfigurator lay
             }
             thisHolder.copyProperties(entry.getValue());
         }
+        for (Map.Entry<Class<? extends ILayoutStrategy>, MapPropertyHolder> entry : layoutConfigurator.childrenLayoutPropertyIndex.entrySet()) {
+            MapPropertyHolder thisHolder = this.childrenLayoutPropertyIndex.get(entry.getKey());
```
Comment (pcdavid) [inline packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/SiriusWebLayoutConfigurator.java:108]: Typo: `thisHol[d]er`

**Review by pcdavid — CHANGES_REQUESTED** [review]
I have not tested yet at runtime, but here are my remarks from reading the PR. I may have more after testing (or not).

**Comment by pcdavid** [comment]
The ADR mentions a "No children" layout strategy, but I'm not sure the code defines/handles one.
The Node.childrenLayoutStategy is optional, but on the backend `NodeComponent` renders its children regardless of the presence of a strategy, and on the front `RectangleView` and `ListView` render all the children nodes they receive unconditionally (it seems).

**Comment by pcdavid** [comment]
On the front, `ImageView.tsx` does not render its children. Frm my understanding it's supposed to be possible to have a node with style "image" and children presented either as a list or free form.

**Comment by pcdavid** [comment]
The commit message (and title) does not reference the correct issue: it should be #1339, not #1139. And this will reveal that the CHANGELOG entry for #1339 is missing.

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java (hunk 3 above)
Comment (gcoutable) [reply packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/components/NodeComponent.java:156]: We should keep it simple. We will think of performance issues when the time has come.

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/LayoutDirection.java (hunk 4 above)
Comment (gcoutable) [reply packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/LayoutDirection.java]: For now, we will only support the `column` direction. I modified the ADR accordingly.
I will remove the enum.

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java (hunk 5 above)
Comment (gcoutable) [reply packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/Node.java]: I will remove it

File: packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodePositionProviderTests.java (hunk 6 above)
Comment (gcoutable) [reply packages/diagrams/backend/sirius-components-diagrams-layout/src/test/java/org/eclipse/sirius/components/diagrams/layout/incremental/NodePositionProviderTests.java]: Done

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/RectangularNodeStyle.java (hunk 7 above)
Comment (gcoutable) [reply packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/RectangularNodeStyle.java]: Done

File: packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/RectangularNodeStyle.java (hunk 8 above)
Comment (gcoutable) [reply packages/diagrams/backend/sirius-components-diagrams/src/main/java/org/eclipse/sirius/components/diagrams/RectangularNodeStyle.java:37]: It could and it will

File: packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/SiriusWebLayoutConfigurator.java (hunk 9 above)
Comment (gcoutable) [reply packages/diagrams/backend/sirius-components-diagrams-layout/src/main/java/org/eclipse/sirius/components/diagrams/layout/SiriusWebLayoutConfigurator.java:108]: the [d] is present.

**Comment by gcoutable** [comment]
> On the front, `ImageView.tsx` does not render its children. Frm my understanding it's supposed to be possible to have a node with style "image" and children presented either as a list or free form.

You can already define NodeDescription represented by an image and a child NodeDescription. Child nodes will overlap the parent background image

**Comment by gcoutable** [comment]
> The commit message (and title) does not reference the correct issue: it should be #1339, not #1139. And this will reveal that the CHANGELOG entry for #1339 is missing.

Updated

**Comment by gcoutable** [comment]
> The ADR mentions a "No children" layout strategy, but I'm not sure the code defines/handles one. The Node.childrenLayoutStategy is optional, but on the backend `NodeComponent` renders its children regardless of the presence of a strategy, and on the front `RectangleView` and `ListView` render all the children nodes they receive unconditionally (it seems).

I removed the mention of NoChildrenLayoutStrategy in the ADR.
I don't think the rendering process will be modified, only the layout engine will be.

File: packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java (hunk 1 above)
Comment (gcoutable) [reply packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java]: `AbstractNodeMappingChildrenLayoutSTrategyProvider` is now used. It will return a free form layout strategy if the option is explicitly defined in the VSM and return a list layout strategy only for vertical stack.

File: packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java (hunk 2 above)
Comment (gcoutable) [reply packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java]: `ViewDiagramDescriptionConverter` requires the `variableManager`, and thus, the function returned by _NodeDescription#getChildrenLayoutStrategy()_. By extension, the variable manager is provided here, even if is not needed.

Comment (pcdavid) [reply packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java]: My remark was about the `private ILayoutStrategy getChildrenLayoutStrategy(VariableManager variableManager)`, whose signature is not constrained (it's private) and whose implementation did not use the `variableManager` passed to it.

Comment (gcoutable) [reply packages/compatibility/backend/sirius-components-compatibility/src/main/java/org/eclipse/sirius/components/compatibility/diagrams/AbstractNodeMappingChilrenLayoutStrategyProvider.java]: Well! I already removed the private method, so, maybe we can consider this "done".

**Review by pcdavid — APPROVED** [review]
