### PR TITLE
[1833] Fix Explorer toolbar and selected item background color width

### LINKED ISSUE #1833: Explorer toolbar and item background color width do not take all space available
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- All

### Screenshots

Capture d’écran 2023-03-03 à 14 52 15

### Steps to reproduce

1. Create/open the Robot Flow demo project
2. Rename one of the Robot item in the explorer with with a very long name
3. Click on the root document tree item
4. Click on the renamed Robot tree item

### Expected behavior

The toolbar takes all the width available, its icons stay on the right.
The selected item's background color takes all the width available.

### Actual behavior

The toolbar only takes the min width, its icons do not stay on the right.
The selected item's background color takes the min width.

### PR DESCRIPTION
**Pull request by AxelRICHARD**
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1833

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx [hunk 1]
```diff
@@ -10,11 +10,20 @@
...
  *******************************************************************************/
+import { makeStyles } from '@material-ui/core/styles';
 import { useEffect, useRef } from 'react';
 import { TreeItem } from '../treeitems/TreeItem';
 import { TreeProps } from './Tree.types';
 
+const useTreeStyle = makeStyles((_) => ({
+  ul: {
+    width: 'fit-content',
+    minWidth: '-webkit-fill-available; min-width: -moz-available',
```
Comment (sbegaudeau) [inline packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx]: I don't feel confortable moving forward with CSS values that are barely out of a working draft for some and others which are still in a working draft. If a child DOM element needs to occupy a specific space, then its parent should determine how to layout it

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx (hunk 1 above)
Comment (AxelRICHARD) [reply packages/trees/frontend/sirius-components-trees/src/trees/Tree.tsx]: Done

**Review by sbegaudeau — APPROVED** [review]
I'll wait for the build and merge it
