### PR TITLE
[5312] Fix an issue where a relation-based edge could be displayed twice in the diagram

### LINKED ISSUE #5312: RelationBasedEdges can be displayed twice
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2025.6.11
* [x] **I have specified my environment** : 
- All

### Steps to reproduce

A model contains an Element A. Element A contains Element B. Element B contains Element C.

A View DiagramDescription allows to display Node A, Node B and Node C as diagram root nodes.
A containment relation-based edge allows to link `Node A -> Node B` and `Node B -> Node C`.
A free-from compartment node is also present on each node allowing to display its children as Nodes.

So for the model described above
 - Element A is displayed one time in the diagram (as root Node).
 - Element A has a compartment Node, this compartment displays Element B.
 - Element B is displayed two times in the diagram (as root Node, and as child node of Element A).
 - Both Element B have a compartment Node, this compartment displays Element C.
 - Element C is displayed three times in the diagram (as root Node, and as child node of both Element B).
 - Element C has a compartment Node, this compartment displays nothing.

Use the following studio and instance projects:
[Studio-ARI-20250807.zip](https://github.com/user-attachments/files/21711243/Studio-ARI-20250807.zip)
[Instance-ARI-20250807.zip](https://github.com/user-attachments/files/21711242/Instance-ARI-20250807.zip)

The problem comes from `RelationBasedSemanticElementsProvider` which allows to return several times the same elements.

### Expected behavior

A relation-based edge of the given studio between two Nodes should be displayed only once.

### Actual behavior

A relation-based edge of the given studio between two Nodes should is displayed twice.

### PR DESCRIPTION
**Pull request by AxelRICHARD**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/5312

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java [hunk 1]
```diff
@@ -0,0 +1,257 @@
...
+    private CreateChildMutationRunner createChildMutationRunner;
+
+    @Autowired
+    private RelationBasedEdgeDiagramDescriptionProvider relationBasedEdgeDescriptionProvider;
+
+    private AtomicReference<UUID> documentId;
+
+    private AtomicReference<String> rootObjectId;
+
+    private AtomicReference<String> entityObjectId;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java]: Don't make tests stateful

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java [hunk 2]
```diff
@@ -0,0 +1,257 @@
...
+            String objectId = JsonPath.read(result, "$.data.createChild.object.id");
+            assertThat(objectId).isNotBlank();
+            this.entityObjectId.set(objectId);
+
+            String objectKind = JsonPath.read(result, "$.data.createChild.object.kind");
+            assertThat(objectKind).isEqualTo("siriusComponents://semantic?domain=rbeDomain&entity=Entity");
+
+        };
+        return createEntityChildTask;
+    }
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java]: Why all those steps? You should be able to do things way more easily with an `ExecuteEditingContextFunctionInput`.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/RelationBasedEdgeDiagramDescriptionProvider.java [hunk 3]
```diff
@@ -0,0 +1,254 @@
...
+        Relation subEntities = DomainFactory.eINSTANCE.createRelation();
+        subEntities.setContainment(true);
+        subEntities.setMany(true);
+        subEntities.setName("subEntities");
+        subEntities.setOptional(true);
+        subEntities.setTargetType(entity);
+        entity.getRelations().add(subEntities);
+        myDomain.getTypes().add(root);
+        myDomain.getTypes().add(entity);
+        return myDomain;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/RelationBasedEdgeDiagramDescriptionProvider.java]: This could be more readable

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/RelationBasedEdgeService.java [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+import org.eclipse.sirius.components.diagrams.renderer.DiagramRenderingCache;
+
+/**
+ * Services for {@link RelationBasedEdgeDiagramDescriptionProvider}.
+ *
+ * @author arichard
+ */
+public class RelationBasedEdgeService {
+
+    public boolean isAncestorOf(org.eclipse.sirius.components.representations.Element parentNodeElement, org.eclipse.sirius.components.representations.Element childNodeElement,
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/RelationBasedEdgeService.java]: Why the fully qualified imports?

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/RelationBasedSemanticElementsProvider.java [hunk 5]
```diff
@@ -38,7 +39,7 @@ public RelationBasedSemanticElementsProvider(List<String> sourceNodeDescriptionI
 
     @Override
     public List<?> apply(VariableManager variableManager) {
-        List<Object> objects = new ArrayList<>();
+        Set<Object> objects = new HashSet<>();
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/RelationBasedSemanticElementsProvider.java]: Prefer a LinkedHashSet, there's no need to lose the order of the collection

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/RelationBasedEdgeDiagramDescriptionProvider.java (hunk 3 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/RelationBasedEdgeDiagramDescriptionProvider.java]: Ok I will add some empty lines if that's what you're talking about.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java (hunk 2 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java]: Ok but how? I can't create those objects easily because there is no EMF Factory for that.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/RelationBasedEdgeService.java (hunk 4 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/RelationBasedEdgeService.java]: Because of a copy/paste.
I will add the corresponding imports.

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/RelationBasedSemanticElementsProvider.java (hunk 5 above)
Comment (AxelRICHARD) [reply packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/RelationBasedSemanticElementsProvider.java]: Ok

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java (hunk 1 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java]: done

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java (hunk 2 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/diagrams/RelationBasedEdgeControllerTests.java]: I've tried using ExecuteEditingContextFunctionInput. Hope that should be more suitable for you.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/EmptyDocumentStereotypeHandler.java [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+import org.eclipse.sirius.web.application.views.explorer.services.ExplorerDescriptionProvider;
+import org.springframework.stereotype.Service;
+
+/**
+ * IStereotypeHandler test allowing to create an empty document.
+ *
+ * @author arichard
+ */
+@Service
+public class EmptyDocumentStereotypeHandler implements IStereotypeHandler {
```
Comment (AxelRICHARD) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/diagrams/EmptyDocumentStereotypeHandler.java]: Sorry I forgot to remove this file, it is useless with the latest version of the PR.

**Comment by AxelRICHARD** [comment]
@sbegaudeau I will fix the compilation error about com.google.common.base et remove the useless file

**Review by sbegaudeau — COMMENTED** [review]
I've reworked the test to ensure that it matches what we accept in terms of best practices. I've thus removed the use of Guava (funnily enough, our architectural tests are not run on those tests, I'll have to fix that in the future) and I've split the responsibilities of the code more clearly. I don't need the use of the AtomicReference as some sort of callback to extract the id.

I'll rebase the PR and merge it after the build. I'll add a more PR and perform a release just after.

**Review by sbegaudeau — APPROVED** [review]
