### PR TITLE
[2614] Remember the last tool invoked in a tool section

### LINKED ISSUE #2614: When invoking a tool from a tool section with multiple choices, the last one invoked should become the default
**Steps to reproduce:**
1. Create/open a Domain diagram (React Flow mode).
2. Create an _Entity_ if needed.
3. Click on the _Entity_, its palette opens.
4. The tool section for attribute creation defaults to "Text" attributes.
5. Open the tool section and select "Boolean". A boolean attribute is created.
6. Re-open the entity's palette

**Expected**: the "Boolean" creation tool should now be the default proposed for the tool section as it is the last one invoked.

**Actual**: the default is still the "Text" attribute creation tool.

[Capture vidéo du 2023-11-22 09-28-32.webm](https://github.com/eclipse-sirius/sirius-web/assets/10608/8bb076ed-2eaa-4e62-beb6-d1d05224b2c5)

### PR DESCRIPTION
**Pull request by pcdavid**

### CODE REVIEW

**Comment by pcdavid** [comment]
I'm working on a Cypress test, but the fix itself can be reviewed in the meantime.

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx [hunk 1]
```diff
@@ -25,8 +25,15 @@ const computePalettePosition = (event: MouseEvent | React.MouseEvent, bounds?: D
...
-  const { x, y, isOpened, hideDiagramPalette, showDiagramPalette } =
-    useContext<DiagramPaletteContextValue>(DiagramPaletteContext);
+  const {
+    x,
+    y,
+    isOpened,
+    hideDiagramPalette,
+    showDiagramPalette,
+    getLastToolInvoked: getDefaultTool,
+    setLastToolInvoked: setDefaultTool,
```
Comment (frouene) [inline packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx]: Why rename these parameters ?

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.types.ts [hunk 2]
```diff
@@ -17,6 +17,8 @@ export interface DiagramPaletteContextValue {
   isOpened: boolean;
   showDiagramPalette: (x: number, y: number) => void;
   hideDiagramPalette: () => void;
+  getLastToolInvoked: (toolSectionId: string) => string | undefined;
+  setLastToolInvoked: (toolSectionId: string, toolId: string) => void;
 }
```
Comment (frouene) [inline packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.types.ts]: Wouldn't it be more accurate to call these methods `getLastToolIdInvoked` and `setLastToolIdInvoked` ?

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.tsx [hunk 3]
```diff
@@ -43,6 +47,24 @@ export const DiagramPaletteContextProvider = ({ children }: DiagramPaletteContex
...
 
+  const getLastToolInvoked = (toolSectionId: string) => {
+    return state.lastToolsInvoked.find(
+      (toolSectionWithDefaultTool) => toolSectionWithDefaultTool.toolSectionId === toolSectionId
+    )?.lastToolId;
+  };
+
+  const setLastToolInvoked = (toolSectionId: string, toolId: string) => {
+    const lastToolsInvoked: ToolSectionWithLastTool[] = state.lastToolsInvoked;
+    if (lastToolsInvoked.some((ts) => ts.toolSectionId === toolSectionId)) {
```
Comment (frouene) [inline packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.tsx]: Details, but I don't see why this variable is named `ts`, it's not a toolSection.

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.types.ts [hunk 4]
```diff
@@ -18,4 +18,6 @@ export interface UseDiagramPaletteValue {
   hideDiagramPalette: () => void;
   showDiagramPalette: (x: number, y: number) => void;
   onDiagramBackgroundClick: (event: React.MouseEvent<Element, MouseEvent>) => void;
+  getLastToolInvoked: (toolSectionId: string) => string | undefined;
```
Comment (sbegaudeau) [inline packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.types.ts]: Please prefer using `null` as we do pretty much every time to explicitly tell consumers that we are returning the lack of a value on purpose.

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx (hunk 1 above)
Comment (pcdavid) [reply packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx]: Incomplete refactoring, I'll fix it.

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.types.ts (hunk 2 above)
Comment (pcdavid) [reply packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.types.ts]: Actually I'll see if I can put the actuall `GQLTool` here instead of just its id.

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.types.ts (hunk 4 above)
Comment (pcdavid) [reply packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.types.ts]: Done.

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.tsx (hunk 3 above)
Comment (pcdavid) [reply packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.tsx]: Done.

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.types.ts (hunk 2 above)
Comment (pcdavid) [reply packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/DiagramPaletteContext.types.ts]: Done.

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx (hunk 1 above)
Comment (pcdavid) [reply packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/palette/useDiagramPalette.tsx]: Done.

**Review by frouene — APPROVED** [review]
