### PR TITLE
[1470] Add EKeys to containment references in view metamodels

### LINKED ISSUE #1470: The id of a converted DiagramDescription/NodeDescription/etc. depend on its index in the View model, which is not stable
In `ViewDiagramDescriptionConverter.convert(RepresentationDescription, AQLInterpreter)`  when we convert a View-based DiagramDescription into an actual Java DiagramDescription, we do this:

```java
String diagramDescriptionURI = EcoreUtil.getURI(viewDiagramDescription).toString();
return DiagramDescription.newDiagramDescription(UUID.nameUUIDFromBytes(diagramDescriptionURI.getBytes()).toString())
```

i.e. the id of the resulting DiagramDescription is based on the View model element's URI... which includes its index. Something like `sirius:///d79a46d4-272b-49f9-b1a5-747f778853ea#//@descriptions.1`. This index is *not* stable.

1. Create a View model with two diagram descriptions D1 and D2 (they can be empty).
2. In another project, create an instance of D2.
3. Go back in the View model, and delete D1. It was not used anywhere so this should not have any impact.
4. Try to reopen the instance of D2:

```
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221) ~[na:na]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramContext.update(DiagramContext.java:53) ~[sirius-components-collaborative-diagrams-2022.9.8.jar:2022.9.8]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramEventProcessor.<init>(DiagramEventProcessor.java:89) ~[sirius-components-collaborative-diagrams-2022.9.8.jar:2022.9.8]
	at org.eclipse.sirius.components.collaborative.diagrams.DiagramEventProcessorFactory.createRepresentationEventProcessor(DiagramEventProcessorFactory.java:82) ~[sirius-components-collaborative-diagrams-2022.9.8.jar:2022.9.8]
```

Indeed, we try to find the diagram description for D2, but it does not exist anymore at the expected id. Because we re-convert the current version of the View model on-demand, `DynamicRepresentationDescriptionService.findDynamicRepresentationDescriptions(IEditingContext)` will return, for the same D2 description, a Java DiagramDescription with a different id.

Note that in this particular case the id we search for does not exist anymore.
I think it is also possible (though I have not tested) for a diagram to "change its nature", for example if in the View model I had a D3 *after* D2. Once D1 is removed, D3 "steals" the id previously used by D2. Re-opening an existing D2 instance would transform it into a D3...

### PR DESCRIPTION
**Pull request by gdaniel**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/1470

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Comment by gdaniel** [comment]
@sbegaudeau @AxelRICHARD Please note that this change is a breaking change: it is not possible to open existing representations once these change have been applied, because the ID of these representations is not valid anymore (they contain a sourceElementId that is computed from an URI with an index, which doesn't match the new URI of the representations with EKeys.
You can test it by creating a diagram on master, switch on this branch -> you can't open it anymore.

**Comment by gdaniel** [comment]
@sbegaudeau There is a failure in the continuous integration regarding coverage of `sirius-components-view-diagram`. I didn't add any actual code in this module, I just updated the ecore and re-generated the code. I assume the new version of the generated code contains more lines than the previous version, which causes the check to fail.
Let me know what I should do to fix this.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/FormVariableViewPreEditingContextProcessor.java [hunk 1]
```diff
@@ -46,7 +45,7 @@
 @Service
 public class FormVariableViewPreEditingContextProcessor implements IEditingContextProcessor  {
 
-    public static final String REPRESENTATION_DESCRIPTION_ID = "siriusComponents://representationDescription?kind=formDescription&sourceKind=view&sourceId=c70a4bb6-7310-335d-bda7-a4d1b7c5486f&sourceElementId=e932123d-b916-3537-84d2-86a4f5873d93";
+    public static final String REPRESENTATION_DESCRIPTION_ID = "siriusComponents://representationDescription?kind=formDescription&sourceKind=view&sourceId=c70a4bb6-7310-335d-bda7-a4d1b7c5486f&sourceElementId=f9e6f70f-935f-3b30-9139-640f43de5da7";
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/FormVariableViewPreEditingContextProcessor.java]: The pattern used in this test will have to be updated to match new tests which do not need to keep such id since it's painful to update when the view model is updated.

File: packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FormEditPlugin.java [hunk 2]
```diff
@@ -90,15 +90,8 @@ protected static String extensionFor(String key) {
...
-            if ("png".equalsIgnoreCase(extension) ||
-                "gif".equalsIgnoreCase(extension) ||
-                "bmp".equalsIgnoreCase(extension) ||
-                "ico".equalsIgnoreCase(extension) ||
-                "jpg".equalsIgnoreCase(extension) ||
-                "jpeg".equalsIgnoreCase(extension) ||
-                "tif".equalsIgnoreCase(extension) ||
-                "tiff".equalsIgnoreCase(extension) ||
-                "svg".equalsIgnoreCase(extension)) {
+            if ("png".equalsIgnoreCase(extension) || "gif".equalsIgnoreCase(extension) || "bmp".equalsIgnoreCase(extension) || "ico".equalsIgnoreCase(extension) || "jpg".equalsIgnoreCase(extension)
```
Comment (sbegaudeau) [inline packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FormEditPlugin.java]: Formatting

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
This seems good on paper, I'll have to play with it a little to see if I can find any issue. I'll update the test and merge it if I don't find anything odd :+1:

File: packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FormEditPlugin.java (hunk 2 above)
Comment (gdaniel) [reply packages/view/backend/sirius-components-view-form-edit/src/main/java/org/eclipse/sirius/components/view/form/provider/FormEditPlugin.java]: Fixed

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/FormVariableViewPreEditingContextProcessor.java (hunk 1 above)
Comment (gdaniel) [reply packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/FormVariableViewPreEditingContextProcessor.java]: Ok I'll let you update the test as you want

**Comment by sbegaudeau** [comment]
I've fixed the code coverage, I'll wait for the build and merge it

**Review by sbegaudeau — APPROVED** [review]
