### PR TITLE
[2509] Fix graphical DnD on high-depth level in some cases

### LINKED ISSUE #2509: Graphical Dnd is not possible on container node description from hight depth level
Graphical DnD is only possible on container display on the diagram or on container in an other container. On deeper container (for example a container in an other container contained in an other one), graphical DnD is not authorized. The container is not fade but it is not highlighted 

* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have specified the version** : 2023.10.4
* [X] **I have specified my environment** :  Windows 11

### Screenshots

failGraphicalDnD

### Steps to reproduce

Create 3 nested containers and try to DnD a node description on the deepest container.  It should work.

### Expected behavior

It should be possible to DnD element graphically on each container, whatever their depth level on the diagram. 

### Actual behavior

It is only possible to DnD element graphically on node description on the first or second depth level.

### PR DESCRIPTION
**Pull request by frouene**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/2509

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.tsx [hunk 1]
```diff
@@ -170,18 +181,11 @@ export const useDropNode = (): UseDropNodeValue => {
...
-          } else {
-            return 0;
-          }
-        });
-      const newParentId = intersections[0]?.id || null;
+      const intersections = getIntersectingNodes(node);
+      const newParentId =
+        [...intersections]
+          .filter((intersectingNode) => !isDescendantOf(draggedNode, intersectingNode, getNodeById))
+          .sort((n1, n2) => getNodeDepth(n2, intersections) - getNodeDepth(n1, intersections))[0]?.id || null;
```
Comment (pcdavid) [inline packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.tsx:188]: Technically there might be a potential performance issue with large diagrams.

* `getNodeDepth` will invoke `intersections.find()` ( _O(n)_) for each depth level
* `sort()` will itself invoke `getNodeDepth` twice for each pair-wise comparison (_O(2*n*log(n))_ comparisons).

But the depth of a given intersecting (and non descendant) node is fixed, and could be computed once.

Of course this is theoretical nitpicking, I have not measured.

**Review by pcdavid — APPROVED** [review]

File: packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.tsx (hunk 1 above)
Comment (pcdavid) [reply packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.tsx:188]: Actually this might not be theoretical:

https://github.com/eclipse-sirius/sirius-web/assets/10608/ae912a35-e3a7-4be2-b7c0-7c35f5c380ac

Comment (pcdavid) [reply packages/diagrams/frontend/sirius-components-diagrams-reactflow/src/renderer/dropNode/useDropNode.tsx:188]: I can't reproduce anymore. I say we merge this but keep an eye on this aspect and we can go back to this piece of code if we see the issue again.
