### PR TITLE
[4400] Add response code annotations to REST APIs

### LINKED ISSUE #4400: Swagger page do not display all responses codes of REST APIs
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- master branch 2025/01/10
* [x] **I have specified my environment** : 
- All

### Problem

Swagger page (http://localhost:8080/swagger-ui/index.html) do not display all responses codes of REST APIs.
It only show code 200 for REST APIs.

### Steps to reproduce

Just access to the Swagger page (http://localhost:8080/swagger-ui/index.html) of a Sirius Web server.

### Expected behavior

Swagger page (http://localhost:8080/swagger-ui/index.html) display all responses codes of REST APIs.

### Actual behavior

Swagger page (http://localhost:8080/swagger-ui/index.html) do not display all responses codes of REST APIs.

### PR DESCRIPTION
**Pull request by AxelRICHARD**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/4400

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [x] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java [hunk 1]
```diff
@@ -55,6 +61,14 @@ public ObjectRestController(IEditingContextDispatcher editingContextDispatcher)
     }
 
     @Operation(description = "Get all the elements in a given project at the given commit.")
+    @ApiResponses(value = {
+        @ApiResponse(responseCode = "200", description = "OK", content = {
+            @Content(mediaType = "application/json", examples = {
+                @ExampleObject(value = "[{\"@id\":\"9f2e43d4-2f7e-49f1-816a-a4e0d3d1f370\", \"attribute1\":\"hello\"}, {\"@id\":\"bab1f7be-82e0-4d14-bc60-b12a60c46f2f\", \"attribute1\":\"bye\"}]")
+            })
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java:66]: I don't really mind but is there a specific reason why you have here an example and on other APIs returning one or more objects you have instead a schema with a reference to `Object.class`?

Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java:66]: `Object.class` returns 
```
[{}]
```
as example.

Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java:66]: Yes I saw that, it's just that the API to return all the elements will display this:

Capture d’écran 2025-01-13 à 11 01 16


While the API to return one of those elements will only display that:

Capture d’écran 2025-01-13 à 11 01 28


One could expect that in the second use case the example would display the same level of details. I'm not against merging things like that, I just want to be sure that it's not an issue for your consumers in SysON. No-one is really using this in Sirius Web today.

It's just to be sure that it's not a typo, that you are aware of this difference.

Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java:66]: May be I have missed one case?

Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java:66]: Yes I have :)

Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java:66]: I will fix that soon

Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/controllers/ObjectRestController.java:66]: Done

**Review by sbegaudeau — APPROVED** [review]
