### PR TITLE
[5220] Use ClickAwayListener to close the palette instead of relying …

### LINKED ISSUE #2754: Palette is sometimes hidden by the properties view
When user display palette tool too closer from the properties view, the palette is hidden by the Properties view. 

* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have checked that this bug appears on Chrome**
* [X] **I have specified the version** : 2023.10.9
* [X] **I have specified my environment** :  Windows 11

### Screenshots

hiddenPalette

### Steps to reproduce

1- Open a diagram
2- Display the palette close to the properties view

### Expected behavior

When user display palette tool too closer from the properties view, the palette should be displayed completely on the left instead of the right if there is not enough space

### Actual behavior

When user display palette tool too closer from the properties view, the palette is hidden by the Properties view.

### LINKED ISSUE #4293: The node palette is displayed above side panels
### Steps to reproduce

1. Creates a flow project and open a diagram
2. Displays the node palette
3. Increase the size one of the side panel until the palette overlaps the panel

### Actual behavior

The node palette is overlapping the panel
image

### Expected behavior

Sliding a panel could close the palette

### LINKED ISSUE #4573: Adapt the palette size to its content
The palette should have a maximum height but not a minimum one.

Image

Image

### LINKED ISSUE #5220: Use ClickAwayListener to close the palette instead of relying on several xyflow events

### PR DESCRIPTION
**Pull request by mcharfadi**
…on several xyflow events

Bug: https://github.com/eclipse-sirius/sirius-web/issues/5220

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx [hunk 1]
```diff
@@ -27,12 +27,15 @@ import { useDiagramPalette } from '../useDiagramPalette';
 import { PaletteToolListProps, PaletteToolListStateValue } from './PaletteToolList.types';
 import { PaletteToolSectionList } from './PaletteToolSectionList';
 
+const listMaxHeight = 220;
```
Comment (gcoutable) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/tool-list/PaletteToolList.tsx]: Can you put directly the value in the style?

**Review by gcoutable — CHANGES_REQUESTED** [review]
I found two strange behaviors:

https://github.com/user-attachments/assets/42c69180-6547-4b05-8c3a-626af595ddc9

https://github.com/user-attachments/assets/7b6bb281-1f61-49e4-a95c-ecb488399920

**Review by gcoutable — APPROVED** [review]
Can be merged on cooldown branch after the build has finished.

**Comment by sbegaudeau** [comment]
If you want to merge things like that in the cooldown branch, please make sure that the CHANGELOG entry is in the right release. I'll fix that in another PR.
