### PR TITLE
[3424] Fix document migration data during creation

### LINKED ISSUE #3424: Wrong migration version for newly created model
The migration version for newly created model should be the version of the more recent IParticipant added, it is currently 0 like uploaded models that have never been migrated.

### PR DESCRIPTION
**Pull request by mcharfadi**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/3424

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLabelExpressionMigrationParticipant.java [hunk 1]
```diff
@@ -35,7 +35,7 @@
 @Service
 public class NodeDescriptionLabelExpressionMigrationParticipant  implements IMigrationParticipant {
 
-    private static final String PARTICIPANT_VERSION = "2024.4.0";
+    private static final String PARTICIPANT_VERSION = "2024.3.2.22.0.0";
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLabelExpressionMigrationParticipant.java]: I somehow missed that but we discussed in details about the shape that was expected for the migration participant version and I don't understand what this is supposed to be (what is this 22 for example?). I don't know what this is supposed to be. I need an iteration, a date and some time, something like this `2024.8.0-202407121400`. It needs to be more specific in the ADR.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/DefaultDomainResourceProvider.java [hunk 2]
```diff
@@ -37,6 +41,12 @@ public class DefaultDomainResourceProvider implements IDefaultDomainResourceProv
 
     private static final String DOMAIN_DOCUMENT_NAME = "DomainNewModel";
 
+    private final List<IMigrationParticipant> migrationParticipants;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/DefaultDomainResourceProvider.java:44]: It will not be viable in the long run to ask everybody to get injected with this every time they want to create a new resource.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/StudioStereotypeHandler.java [hunk 3]
```diff
@@ -43,8 +45,11 @@ public class StudioStereotypeHandler implements IStereotypeHandler {
 
     private final IDomainNameProvider domainNameProvider;
 
-    public StudioStereotypeHandler(IDomainNameProvider domainNameProvider) {
+    private final List<IMigrationParticipant> migrationParticipants;
+
+    public StudioStereotypeHandler(IDomainNameProvider domainNameProvider, List<IMigrationParticipant> migrationParticipants) {
         this.domainNameProvider = Objects.requireNonNull(domainNameProvider);
+        this.migrationParticipants = migrationParticipants;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/StudioStereotypeHandler.java]: Why is null acceptable?

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/DefaultDomainResourceProvider.java (hunk 2 above)
Comment (mcharfadi) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/DefaultDomainResourceProvider.java:44]: Would setting the correct migrationData in `StudioProjectTemplateInitializer` be more acceptable then ?

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLabelExpressionMigrationParticipant.java (hunk 1 above)
Comment (mcharfadi) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLabelExpressionMigrationParticipant.java]: I updated the ADR in order to be more precise about the version of participants

File: doc/adrs/144_add_support_for_emf_models_migration.adoc [hunk 4]
```diff
@@ -18,6 +18,10 @@ One important thing to consider is that BasicExtendedMetaData methods assume tha
 
 The version of the last migration used on a model will be stored at the root of the JSON document on EMFJson side.
 
+The version of a migration participant will represent when it was added to the project and will respect this structure : `ITERATION-YYYYMMDDHHMM`
+
+For example `2024.3.2-202404221400` for a participant added the 22-04 2024 at 14h00 during the iteration 2024.3.2.
```
Comment (sbegaudeau) [inline doc/adrs/144_add_support_for_emf_models_migration.adoc]: An iteration version can only end in `.0` so the version number would be `2024.5.0-202404221400` to indicate a migration participant contributed during the development of 2024.5.0

File: doc/adrs/144_add_support_for_emf_models_migration.adoc [hunk 5]
```diff
@@ -65,15 +69,15 @@ public interface IMigrationParticipant {
...
+This is an example of implementation where this NameFeatureChangelMigrationParticipant will be used if the model version is superior to `2024.3.2-202404221400`.
 If the feature name was changed from "name2" to something else, we provide the new correct value.
 
 [source,java]
 ----
 @Service
 public class NameFeatureChangelMigrationParticipant implements IMigrationParticipant {
 
-    private static final String PARTICIPANT_VERSION = "202404221458";
+    private static final String PARTICIPANT_VERSION = "2024.3.2-202404221400";
```
Comment (sbegaudeau) [inline doc/adrs/144_add_support_for_emf_models_migration.adoc]: 2024.5.0

File: doc/adrs/144_add_support_for_emf_models_migration.adoc [hunk 6]
```diff
@@ -65,15 +69,15 @@ public interface IMigrationParticipant {
 ----
 
 
-This is an example of implementation where this NameFeatureChangelMigrationParticipant will be used if the model version is superior to `202404221458`.
+This is an example of implementation where this NameFeatureChangelMigrationParticipant will be used if the model version is superior to `2024.3.2-202404221400`.
```
Comment (sbegaudeau) [inline doc/adrs/144_add_support_for_emf_models_migration.adoc]: 2024.5.0

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLabelExpressionMigrationParticipant.java [hunk 7]
```diff
@@ -35,7 +35,7 @@
 @Service
 public class NodeDescriptionLabelExpressionMigrationParticipant  implements IMigrationParticipant {
 
-    private static final String PARTICIPANT_VERSION = "2024.4.0";
+    private static final String PARTICIPANT_VERSION = "2024.3.2-202404221400";
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/migration/participants/NodeDescriptionLabelExpressionMigrationParticipant.java]: 2024.5.0

**Review by sbegaudeau — COMMENTED** [review]
I'll update this tiny detail and merge it

**Comment by sbegaudeau** [comment]
I'll wait for the build and merge it just after

**Review by sbegaudeau — APPROVED** [review]
