### PR TITLE
[1485] Select the relevant edge reconnection tools

### LINKED ISSUE #1485: Only the first defined reconnection tool is executed no matter how any of them are defined in a view model
### Steps to reproduce

1. Import the following project in sirius-web [reconnection-issue.zip](https://github.com/eclipse-sirius/sirius-components/files/10083462/reconnection-issue.zip)
2. Create a `New Representation root` diagram on _instance/Root_ element
3. You should see two edges, they are defined as followed:
  a. Reconnecting _increase_ from _t0_ to _t1_ should increase the _Entity_ counter by 1
  b. Reconnecting _decrease_ from _t0_ to _t1_ should decrease the _Entity_ counter by 1
4. Reconnect _increase_ from _t0_ to _t1_ then reconnect _decrease_ from _t0_ to _t1_

### Expected behavior

The _Entity_ counter should be equal to `0`

### Actual behavior

The _Entity_ counter is equal to `-2` or `2`, it will depend on which one of the reconnection tools has been converted from View DSL.

### PR DESCRIPTION
**Pull request by sbegaudeau**
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1485
Signed-off-by: Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java [hunk 1]
```diff
@@ -79,4 +138,37 @@ private VariableManager createVariableManager(ReconnectionToolInterpreterData to
...
+                    } catch (BeansException beansException) {
+                        this.logger.warn("Error while trying to instantiate Java service class " + serviceClass.getName(), beansException); //$NON-NLS-1$
+                        return null;
+                    }
+                })
+                .filter(Objects::nonNull)
+                .collect(Collectors.toList());
+        // @formatter:on
+        return new AQLInterpreter(List.of(), serviceInstances, visibleEPackages);
+    }
```
Comment (pcdavid) [inline packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java:172]: This is a recurring need, and these lines are duplicated in several places (not always exactly identical, sometimes for good reasons sometimes because they evolved independently).
I'm not sure which mecahnism would be the best, but we should have a way to share these instances in the relevant scopes.

Comment (sbegaudeau) [reply packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java:172]: I think that pretty much every location where these pieces of code are currently used will be re-written or heavily impacted when we will start working on [this issue](https://github.com/eclipse-sirius/sirius-components/issues/1422).

The code that you have highlighted and a bit more above too will have to be thrown away soon.

**Review by pcdavid — APPROVED** [review]

File: packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java (hunk 1 above)
Comment (pcdavid) [reply packages/view/backend/sirius-components-view-emf/src/main/java/org/eclipse/sirius/components/view/emf/diagram/ViewReconnectionToolsExecutor.java:172]: FYI I had to do the same in the "AQL completion" PR as I need an interpreter to answer the completion query, and this is in a context outside of a diagram rendering or "classical" tool application.
There is also one instance in `ViewInitialDirectEditElementLabelProvider.createInterpreter(View, IEditingContext)` as it needs the evaluate AQL expressions tool.
