### PR TITLE
[5101] Remove state machine from Workbench and EditProjectView

### LINKED ISSUE #4816: Cannot navigate to another project from an open project
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
- other: please specify
* [x] **I have specified my environment** : 
- my computer: Windows

### Steps to reproduce

Add the following lines in `DefaultExtensionRegistry` (**use an existing projectId**)

```
export const TestButtonContribution = ({}: NavigationBarMenuItemProps) => {
  return (
    <MenuItem component={RouterLink} to="/projects/<PROJECT ID>/edit">
      <ListItemIcon>
        <FileCopyIcon />
      </ListItemIcon>
      <ListItemText primary="TestButton" />
    </MenuItem>
  );
};

defaultExtensionRegistry.addComponent(navigationBarMenuEntryExtensionPoint, {
  identifier: `siriusweb_${navigationBarMenuEntryExtensionPoint.identifier}_test`,
  Component: TestButtonContribution,
});
```

This adds a TestButton menu item in the top-right menu, with a link to a project.
Click on the TestButton item from the home page: the project is opened
Go back to the home page and open another project
Click on the TestButton item: the URL is set with the new projectId, but the workbench doesn't contain the other project.

Note that a `getProjectAndRepresentation ` GraphQL query is fired when clicking on TestButton, but the other queries that are typically fired when loading a project aren't. This could indicate an issue in `EditProjectView` or in the state machine it uses.

### LINKED ISSUE #5101: Remove state machine from Workbench and EditProjectView

### PR DESCRIPTION
**Pull request by mcharfadi**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/5101

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [x] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx [hunk 1]
```diff
@@ -171,25 +192,30 @@ export const Workbench = ({
   const { Component: MainComponent } = useComponent(workbenchMainAreaExtensionPoint);
   let main = <MainComponent editingContextId={editingContextId} readOnly={readOnly} />;
 
-  if (displayedRepresentation) {
+  const onRepresentationClick = (representation: RepresentationMetadata) => {
+    setSelection({ entries: [{ id: representation.id }] });
+  };
+
+  if (state.displayedRepresentation) {
+    const metaData = state.displayedRepresentation;
```
Comment (frouene) [inline packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: Variable name `metaData` feel strange to me.
`representationMetadata` seems better I think

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx [hunk 2]
```diff
@@ -171,25 +192,30 @@ export const Workbench = ({
...
     const RepresentationComponent = representationFactories
-      .map((representationFactory) => representationFactory(displayedRepresentation))
+      .map((representationFactory) => representationFactory(metaData))
       .find((component) => component != null);
     const props: RepresentationComponentProps = {
       editingContextId,
       readOnly,
-      representationId: displayedRepresentation.id,
+      representationId: state.displayedRepresentation.id,
```
Comment (frouene) [inline packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: why do not use `metaData` variable

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx [hunk 3]
```diff
@@ -75,86 +54,128 @@ const useWorkbenchStyles = makeStyles()(() => ({
   },
 }));
 
+const isRepresentationRenamedEventPayload = (
+  payload: GQLEditingContextEventPayload | null
+): payload is GQLRepresentationRenamedEventPayload =>
+  !!payload && payload.__typename === 'RepresentationRenamedEventPayload';
+
+const getRepresentationsMetaData = (data: GQLRepresentationMetadataQueryData | null): GQLRepresentationMetadata[] =>
```
Comment (frouene) [inline packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: `getRepresentationMetadata` instead ?

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx [hunk 4]
```diff
@@ -75,86 +54,128 @@ const useWorkbenchStyles = makeStyles()(() => ({
...
+  const { data: representationMetadataQueryData } = useRepresentationMetadata(editingContextId, selection);
+  const { payload: editingContextEventPayload } = useEditingContextEventSubscription(editingContextId);
 
   const { data: representationFactories } = useData(representationFactoryExtensionPoint);
+  useEffect(() => {
+    if (isRepresentationRenamedEventPayload(editingContextEventPayload)) {
+      const { representationId, newLabel } = editingContextEventPayload;
+      const representations = [...state.representations];
+
+      for (var i = 0; i < representations.length; i++) {
```
Comment (frouene) [inline packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: something like 
```
representations.forEach((representation) => {
        if (representation.id === representationId) {
          representation.label = newLabel;
        }
      });
```
feels more readable

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx [hunk 5]
```diff
@@ -75,86 +54,128 @@ const useWorkbenchStyles = makeStyles()(() => ({
...
 
+  // When opening a representation
   useEffect(() => {
-    const updateSelectedRepresentation: UpdateSelectedRepresentationEvent = {
-      type: 'UPDATE_SELECTED_REPRESENTATION',
-      representations: data?.viewer.editingContext.representations.edges.map((edge) => edge.node) ?? [],
-    };
-    dispatch(updateSelectedRepresentation);
-  }, [data, selection, dispatch]);
+    const selectedElementRepresentationMetaData = getRepresentationsMetaData(representationMetadataQueryData);
```
Comment (frouene) [inline packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: `selectedElementRepresentationMetadata` instead

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx [hunk 6]
```diff
@@ -75,86 +54,128 @@ const useWorkbenchStyles = makeStyles()(() => ({
...
-  const onClose = (representation: RepresentationMetadata) => {
-    const hideRepresentationEvent: HideRepresentationEvent = { type: 'HIDE_REPRESENTATION', representation };
-    dispatch(hideRepresentationEvent);
+      setState((prevState) => ({
+        ...prevState,
+        displayedRepresentation: displayedRepresentation ? displayedRepresentation : null,
+        representations: newSelectedRepresentations,
+      }));
+    }
+  }, [representationMetadataQueryData, selection]);
```
Comment (frouene) [inline packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx:124]: `selection` is not used in this useEffect, is it normal to have it as dependency

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx [hunk 7]
```diff
@@ -75,86 +54,128 @@ const useWorkbenchStyles = makeStyles()(() => ({
...
+        ...prevState,
+        displayedRepresentation: null,
+        representations: [],
+      }));
+    } else {
+      const newIndex = newRepresentations.findIndex(
+        (representation) => state.displayedRepresentation && representation.id === state.displayedRepresentation.id
+      );
+
+      if (newIndex !== -1) {
```
Comment (frouene) [inline packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx:148]: Why is this guard necessary?
We do a filter on this list few lines above

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx [hunk 8]
```diff
@@ -63,43 +53,61 @@ const useEditProjectViewStyles = makeStyles()((_) => ({
   },
 }));
 
+type EditProjectViewState = {
```
Comment (frouene) [inline packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx]: To be placed in a dedicated types file

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx [hunk 9]
```diff
@@ -63,43 +53,61 @@ const useEditProjectViewStyles = makeStyles()((_) => ({
...
+  project: GQLProject | null;
+  representation: RepresentationMetadata | null;
```
Comment (frouene) [inline packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx]: Wouldn't it be more meaningful to refer to `representationMetadata` rather only `representation`?

**Review by frouene — CHANGES_REQUESTED** [review]

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx (hunk 7 above)
Comment (mcharfadi) [reply packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx:148]: We're testing if the representation that was closed was the current one.
The filter above remove the representation that was closed from the list of opened representation.

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx (hunk 6 above)
Comment (mcharfadi) [reply packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx:124]: If the current representation was the one that was closed, we need to add selection as a dependency in order to reopen it from the explorer.

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx (hunk 5 above)
Comment (mcharfadi) [reply packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: done

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx (hunk 4 above)
Comment (mcharfadi) [reply packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: done

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx (hunk 3 above)
Comment (mcharfadi) [reply packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: done

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx (hunk 2 above)
Comment (mcharfadi) [reply packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: done

File: packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx (hunk 1 above)
Comment (mcharfadi) [reply packages/core/frontend/sirius-components-core/src/workbench/Workbench.tsx]: done

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx (hunk 8 above)
Comment (mcharfadi) [reply packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx]: done

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx (hunk 9 above)
Comment (mcharfadi) [reply packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx]: I renamed `representations `to `representationsMetadata `
and `displayedRepresentation `to `displayedRepresentationMetaData`

**Review by frouene — APPROVED** [review]

**Comment by sbegaudeau** [comment]
I've merged the branch since it was approved and the build was green
