### PR TITLE
[667]  Restore layout and unsynchronized nodes when importing a project with a diagram

### LINKED ISSUE #667: Representation state is not restored on project upload
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** : 0.3.9
* [x] **I have specified my environment** : Cloud

### Steps to reproduce

1. Export an existing project with diagrams with incremental layout
2. Delete the project
3. Upload the project : for diagrams with manual layout, their layout should correspond to the manual layout at the time of export. But it is not the case, the manual layout is lost.

### Expected behavior

For diagrams with manual layout, their layout should correspond to the manual layout at the time of export.

### Actual behavior

For diagrams with manual layout, their layout don't correspond to the manual layout at the time of export.

### PR DESCRIPTION
**Pull request by mcharfadi**
# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DiagramImporterUpdateService.java [hunk 1]
```diff
@@ -0,0 +1,213 @@
...
+
+    private final Logger logger = LoggerFactory.getLogger(DiagramImporterUpdateService.class);
+
+    public DiagramImporterUpdateService(IEditingContextSearchService editingContextSearchService, ObjectMapper objectMapper, IRepresentationContentUpdateService representationContentUpdateService, IRepresentationSearchService representationSearchService, IRepresentationDescriptionSearchService representationDescriptionSearchService, DiagramCreationService diagramCreationService) {
+        this.editingContextSearchService = editingContextSearchService;
+        this.objectMapper = objectMapper;
+        this.representationContentUpdateService = representationContentUpdateService;
+        this.representationSearchService = representationSearchService;
+        this.representationDescriptionSearchService = representationDescriptionSearchService;
+        this.diagramCreationService = diagramCreationService;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DiagramImporterUpdateService.java]: Objects.requireNonNull

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DiagramImporterUpdateService.java [hunk 2]
```diff
@@ -0,0 +1,213 @@
...
+                    var newNodeId = this.computeNodeId(newRepresentation.get().getId(), oldNode.getDescriptionId(), NodeContainmentKind.CHILD_NODE, semanticElementsIdMappings.get(oldNode.getTargetObjectId()));
+                    nodeElementOldNewIds.put(oldNodeId, newNodeId);
+
+                    oldNode.getChildNodes().forEach(childNode ->
+                        handleChildren(diagramDescription.get(), childNode, newNodeId, NodeContainmentKind.CHILD_NODE, semanticElementsIdMappings, nodeElementOldNewIds, diagramContext));
+                    oldNode.getBorderNodes().forEach(childNode ->
+                        handleChildren(diagramDescription.get(), childNode, newNodeId, NodeContainmentKind.BORDER_NODE, semanticElementsIdMappings, nodeElementOldNewIds, diagramContext));
+                });
+
+                AtomicInteger count = new AtomicInteger();
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/DiagramImporterUpdateService.java:119]: I won't block this PR so close from the release for that but using some concurrent data structure for such a simple need seems odd.

**Review by sbegaudeau — COMMENTED** [review]
I'll try to see how it behaves and I'll integrate it quickly to create a release for SysON at least.

**Comment by sbegaudeau** [comment]
This seems to be working, I'll wait for https://github.com/eclipse-sirius/sirius-web/pull/4983 first and I'll rebase this one to merge it and perform a first release before the real RC1 release.

**Review by sbegaudeau — APPROVED** [review]
