### PR TITLE
[4208] Improve performance of details view rendering on selection change

### LINKED ISSUE #4208: Improve performance of details view rendering on selection change
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- my computer: Linux

### Screenshots

No

### Steps to reproduce

Select different objects in a model

### Expected behavior

A details view is updated slowly, especially if it's pretty complicated

### Actual behavior

It works faster

### PR DESCRIPTION
**Pull request by AresEkb**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/4208

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Comment by AresEkb** [comment]
When you select an object in a model, the `FormBasedView` is rendered 8 times. It works slow for complicated forms

I added memoization to `FormBasedView`

And also removed `useState` and `useEffect` from `DetailsView`. I think they only decrease performance, causes extra renderings. It worked as follows:

1. Selection is changed. So `DetailsView` is rendered
2. 1st `useEffect` compares current selection stored in state and new selection stored in context. And if they differ updates the state. I think there is no reason to store selection twice: in context and in state - context is enough. And also changing the state causes one more `DetailsView` rendering
3. On the next render `objectIds` will have a new value based on new selection. And `useDetailsViewSubscription` requests the new form
4. When the form payload is updated the 2nd `useEffect` is called and updates the state causing rerender
5. At last `DetailsView` is rendered with new state

I think that `useSelection` and `useDetailsViewSubscription` are enough to store the context/state. And local state is not required. Also `useEffect` combined with `setState` complicates logic and causes rerenderings

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/DetailsView.tsx [hunk 1]
```diff
@@ -81,7 +48,7 @@ export const DetailsView = ({ editingContextId, readOnly }: WorkbenchViewCompone
         value={{
           payload: payload,
         }}>
-        <FormBasedView editingContextId={editingContextId} form={state.form} readOnly={readOnly} />
+        <FormBasedView editingContextId={editingContextId} form={payload.form} readOnly={readOnly} />
```
Comment (sbegaudeau) [inline packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/DetailsView.tsx]: Unfortunately this improvement cannot be done, not all payload are or will be `FormRefreshedEventPayload` and as a result, we need to store the latest form in a state. If a new payload `XXX` is emitted by the backend, the form will become blank.

**Review by sbegaudeau — DISMISSED** [review]

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/DetailsView.tsx (hunk 1 above)
Comment (AresEkb) [reply packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/DetailsView.tsx]: Thanks! I reverted the change

What do you think about `currentSelection` stored in local state? Should I revert it as well? I think it's not required, bacause `useSelection()` is just enough. We can get rid of some extra renderings removing `currentSelection` and corresponding `useEffect()` comparing selections

**Review by mcharfadi — APPROVED** [review]
