### PR TITLE
[2348] Fix layout issue with the widget reference

### LINKED ISSUE #2348: Layout issue with the widget reference
There is a layout issue with the widget ref depending on the width of the values.
The button more, add and delete can be partially hidden

https://github.com/eclipse-sirius/sirius-web/assets/128395825/68b02d49-e89f-4669-86cd-be79e041d0b1

### PR DESCRIPTION
**Pull request by frouene**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/2348

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx [hunk 1]
```diff
@@ -140,35 +145,42 @@ export const ValuedReferenceAutocomplete = ({
           placeholder={placeholder}
           InputProps={{
             ...params.InputProps,
+            style: { paddingRight: '84px' },
```
Comment (AxelRICHARD) [inline packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx]: We try to avoid arbitrary values. Could you try something like `theme.spacing(X)`?

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx [hunk 2]
```diff
@@ -140,35 +145,42 @@ export const ValuedReferenceAutocomplete = ({
...
             endAdornment: (
               <>
                 {params.InputProps.endAdornment}
                 <InputAdornment position="end">
```
Comment (AxelRICHARD) [inline packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx]: Is it not possible to add flex layout on `InputAdornment` instead of `className={classes.inputEndButton}` && `style={{ right: ArbitraryValue }}` on each `IconButton`?

**Review by AxelRICHARD — CHANGES_REQUESTED** [review]

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx (hunk 1 above)
Comment (frouene) [reply packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx]: Done

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx (hunk 2 above)
Comment (frouene) [reply packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx]: Yes, you're right, it's better with the style directly on the `InputAdornment `, done.

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx [hunk 3]
```diff
@@ -140,10 +150,11 @@ export const ValuedReferenceAutocomplete = ({
           placeholder={placeholder}
           InputProps={{
             ...params.InputProps,
+            style: { paddingRight: theme.spacing(10) },
```
Comment (AxelRICHARD) [inline packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx:155]: Could you also put this style into the `useStyles` please ? (the same way as the `InputProps` in `ModelBrowserFilterBar`)

**Review by AxelRICHARD — CHANGES_REQUESTED** [review]

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx (hunk 3 above)
Comment (frouene) [reply packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx:155]: It's the `Autocomplete` that customize the textfield style by passing `className` with `...params.InputProps`, if we override it by making our own style we lost some wanted behavior. 
Maybe I missed something but I couldn't do anything other than add style this way.

Comment (AxelRICHARD) [reply packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx:155]: ok

**Review by AxelRICHARD — APPROVED** [review]

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx [hunk 4]
```diff
@@ -10,7 +10,7 @@
  * Contributors:
  *     Obeo - initial API and implementation
  *******************************************************************************/
-import { ServerContext, ServerContextValue } from '@eclipse-sirius/sirius-components-core';
+import { ServerContext, ServerContextValue, theme } from '@eclipse-sirius/sirius-components-core';
```
Comment (sbegaudeau) [inline packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx:13]: The `theme` object imported here is just an helper provided to applications which should create their own theme. This is not the current theme of the application and thus should not be used internally.

You are not using here, the theme of the application.

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx [hunk 5]
```diff
@@ -36,6 +36,16 @@ const useStyles = makeStyles<Theme, GQLReferenceWidgetStyle>((theme) => ({
...
   },
+  endAdornmentButton: {
+    position: 'absolute',
+    top: '50%',
+    transform: 'translateY(-50%)',
+    display: 'flex',
+    right: theme.spacing(2.5),
+    '& > *': {
+      padding: 0,
+    },
```
Comment (sbegaudeau) [inline packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx:47]: The absolute positioning feels odd but why do you need to position things using percentages, translation, fixed size in pixels simultaneously?

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx [hunk 6]
```diff
@@ -142,10 +152,11 @@ export const ValuedReferenceAutocomplete = ({
           helperText={widget.diagnostics[0]?.message}
           InputProps={{
             ...params.InputProps,
+            style: { paddingRight: theme.spacing(10) },
```
Comment (sbegaudeau) [inline packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx:155]: And why 10?

Comment (frouene) [reply packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx:155]: 10 corresponds to the offset required to prevent the values from being displayed below the buttons.
I will add a comment

File: packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx (hunk 5 above)
Comment (frouene) [reply packages/forms/frontend/sirius-components-widget-reference/src/components/ValuedReferenceAutocomplete.tsx:47]: With the last changes, I don't need the top and transform properties, I will change that.
For the rigth, it corresponds to the offset for the actual arrow button that came with the Autocomplete mui component.
