### PR TITLE
[5404] Fix an issue where resetting an appearance was not updating the corresponding input

### LINKED ISSUE #5404: Appearance palette values are not reset
After clicking on reset button in the appearance palette, the value is still the custom one.

### Actual behavior

Image

### PR DESCRIPTION
**Pull request by mcharfadi**
# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hooks/useGetUpdatedModalPosition.tsx [hunk 1]
```diff
@@ -13,11 +13,18 @@
 import { ReactFlowState, useStore, XYPosition } from '@xyflow/react';
 import { UseGetUpdatedModalPositionValue } from './useGetUpdatedModalPosition.types';
 
+const equalityFunction = (oldValue: DOMRect | undefined, newValue: DOMRect | undefined) =>
```
Comment (mcharfadi) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/hooks/useGetUpdatedModalPosition.tsx:16]: This is needed to avoid many rerender

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceColorPicker.tsx [hunk 2]
```diff
@@ -10,29 +10,54 @@
...
   });
 
+  useEffect(() => {
+    if (!state.focused) {
+      setState((prevState) => ({
+        ...prevState,
+        value: initialValue,
+      }));
+    }
+  }, [initialValue]);
```
Comment (frouene) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceColorPicker.tsx:35]: Does the `state.focused` need to be in the dependencies ?

Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/widget/AppearanceColorPicker.tsx:35]: No because I don't want the value to change for `initalValue ` `onBlur`
But you're right that it was missing something, I'll take `prevState.focused `to fix the issue.

File: CHANGELOG.adoc [hunk 3]
```diff
@@ -57,6 +57,8 @@ Downstream projects should stop provide their own implementations.
 - https://github.com/eclipse-sirius/sirius-web/issues/5427[#5427] [diagram] An implementation of `ICustomNodeStyleDeserializer` is required to correctly upload a diagram  with custom nodes.
 - https://github.com/eclipse-sirius/sirius-web/issues/5471[#5471] [diagram] `org.eclipse.sirius.components.diagrams.Label` is now a record
 - https://github.com/eclipse-sirius/sirius-web/issues/5467[#5467] [diagram] To avoid edge blinking when refreshing the diagram, you need to set the property measured.height and measured.width with the value of the node layout data when converting a custom node accordingly to the xyflow https://reactflow.dev/learn/advanced-use/ssr-ssg-configuration#node-dimensions[documentation].
+- https://github.com/eclipse-sirius/sirius-web/issues/5404[#5404] [diagram] The prop `isDisabled` of the `appearance widgets` has been renamed to `disabled` to match the name of the prop used by the underlying input.
+* `element` of `PaletteAppearanceSectionContributionComponentProps` has been `removed`
```
Comment (frouene) [inline CHANGELOG.adoc]: Maybe add how to retrieve it

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/SelectAppearanceProperty.tsx [hunk 4]
```diff
@@ -28,7 +28,7 @@ export const SelectAppearanceProperty = ({
   onChange,
   options,
   onReset,
-  isDisabled,
+  disabled,
```
Comment (frouene) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/SelectAppearanceProperty.tsx:30]: Not related to this PR but there are dead code line 22 and 23

File: CHANGELOG.adoc (hunk 3 above)
Comment (mcharfadi) [reply CHANGELOG.adoc]: done

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/SelectAppearanceProperty.tsx (hunk 4 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/palette/appearance/property-component/SelectAppearanceProperty.tsx:30]: done

**Review by frouene — APPROVED** [review]
