### PR TITLE
[3668] Fix an issue that prevents wrapped label from overflow its con…

### LINKED ISSUE #3668: LabelOverflowStrategy.WRAP may lead to overflow of its container
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2024.5.2
* [x] **I have specified my environment** : 
- All

### Screenshots

Capture d’écran 2024-06-26 à 15 00 45

### Steps to reproduce

Have a compartment item with LabelOverflowStrategy.WRAP.
Set a very long value as label.

### Expected behavior

The label doesn't overflow on its container

### Actual behavior

The label overflows on its container

### PR DESCRIPTION
**Pull request by frouene**
…tainer

Bug: https://github.com/eclipse-sirius/sirius-web/issues/3668

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts [hunk 1]
```diff
@@ -47,8 +47,13 @@ export class ListNodeLayoutHandler implements INodeLayoutHandler<ListNodeData> {
     forceDimensions?: ForcedDimensions
   ) {
     const nodeIndex = findNodeIndex(visibleNodes, node.id);
-    const nodeElement = document.getElementById(`${node.id}-listNode-${nodeIndex}`)?.children[0];
-    const borderWidth = nodeElement ? parseFloat(window.getComputedStyle(nodeElement).borderWidth) : 0;
+    const nodeElement = document.getElementById(`${node.id}-listNode-${nodeIndex}`);
+    const nodeElementChildren =
```
Comment (mcharfadi) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts]: I think it's `nodeElementChild `

File: CHANGELOG.adoc [hunk 2]
```diff
@@ -69,6 +69,7 @@ More existing APIs will be migrated to this new common pattern.
 - https://github.com/eclipse-sirius/sirius-web/issues/3630[#3630] [sirius-web] Restore support for the deletion of dangling representations
 - https://github.com/eclipse-sirius/sirius-web/issues/3666[#3666] [core] Enable EMF's intrinsicIDToEObjectMap for JSON resources to support languages which use modeled identifiers (e.g. SysMLv2).
 - https://github.com/eclipse-sirius/sirius-web/issues/3664[#3664] [core] The Default.svg image is no longer displayed with the new architecture.
+- https://github.com/eclipse-sirius/sirius-web/issues/3668[#3668] [diagram] Fix an issue that prevents wrapped label from overflow its container
```
Comment (mcharfadi) [inline CHANGELOG.adoc]: I think you mean something like `Fix an issue that would cause wrapped label to overflow its container`

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts [hunk 3]
```diff
@@ -47,8 +47,13 @@ export class ListNodeLayoutHandler implements INodeLayoutHandler<ListNodeData> {
...
+      nodeElement?.children &&
+      Array.from(nodeElement.children).filter((child) => !child.classList.contains('react-flow__resize-control'))[0];
```
Comment (mcharfadi) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts:53]: Why filtering out the resize handle ?

**Review by mcharfadi — CHANGES_REQUESTED** [review]
After
Before
It seems that text align LEFT property is not taken into account anymore

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts (hunk 3 above)
Comment (frouene) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts:53]: I have to filter it because when we get the first child (`document.getElementById(`${node.id}-listNode-${nodeIndex}`)?.children[0]` - before), it was the div containing the react flow resizer, so the size was not correct

Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/renderer/layout/ListNodeLayoutHandler.ts:53]: Okay I see, we should give to the needed div a dedicated `id `or `className `but it's out of the scope of this PR.

**Comment by frouene** [comment]
> It seems that text align LEFT property is not taken into account anymore

It seems ok, on my side

image

I don't think you could check it by a label without spaces between words

**Comment by mcharfadi** [comment]
I meant the alignement of the whole label div, on my first screenshot (with your modification) it is centered whereas before it was on the left

**Review by mcharfadi — APPROVED** [review]

**Comment by mcharfadi** [comment]
Actually the issue was on master with icons labels, so this PR solve 2 things
